### ISSUE TITLE
extracted libraries (DLL etc) not deleted properly on exit

### ISSUE THREAD

**Issue by FyiurAmron** [xerial/sqlite-jdbc#87] opened 2016-01-13 21:28 UTC
see https://bitbucket.org/xerial/sqlite-jdbc/issues/202/jdbc-driver-extracts-a-new-dll-library-on#comment-None - firstly, http://bugs.java.com/view_bug.do?bug_id=6357433 - but since we have `                if(writer != null) {
                    writer.close();
                }` and it ain't closed, maybe it's due to the fact that the DLL has been loaded and is not unloaded? ( https://web.archive.org/web/20140704120535/http://www.codethesis.com/blog/unload-java-jni-dll as the possible solution in that case )

Anyway, to allow a manual workaround: maybe keep "extractedLibFile" somewhere, so that the API user can actually *know* what is the lib (DLL) that has been extracted, to allow later cleanup for it (external script or whatever).

**Comment by promille** [comment] 2016-04-06 08:25
I had the same Problem with tons of sqlite.dll's in my tmp dir.

I tried to delete the dll's via an Runtime shutdownHook but the dll's can not be delete.
Yes I think its because the dll is attached to the current running process.

Now I removed the uuid from the extrected dll name and test if the dll is already there -> use it / otherwise copy and use it.

So there will be one dll for each version only without any deletion.

**Comment by gitblit** [comment] 2016-07-01 19:15
This is a duplicate of #80 and is an issue on Windows. *NIX should allow deleting the shared library without a problem, AFAIK.

**Closed** 2016-07-01 21:34 UTC
