### ISSUE TITLE
NPE bug while doing an update operation

### ISSUE THREAD

**Issue by razvanmihaescu** [xerial/sqlite-jdbc#948] opened 2023-08-10 12:47 UTC
Hello

I discovered that with the latest 2 versions of org.xerial:sqlite-jdbc -> 3.41.2.2 & 3.42.0.0, if the first new value of an update operation is null, the update itself crashes with a NPE, the issue is occuring only in this case, if the null value is for the first parameter, any index works fine.

Here is the stack trace:

xception: nullntat org.sqlite.core.CoreStatement.checkIndex(CoreStatement.java:145)ntat org.sqlite.jdbc3.JDBC3PreparedStatement.getParameterType(JDBC3PreparedStatement.java:165)ntat org.springframework.jdbc.core.StatementCreatorUtils.setNull(StatementCreatorUtils.java:253)ntat org.springframework.jdbc.core.StatementCreatorUtils.setParameterValueInternal(StatementCreatorUtils.java:234)ntat org.springframework.jdbc.core.StatementCreatorUtils.setParameterValue(StatementCreatorUtils.java:168)ntat org.springframework.jdbc.core.ArgumentPreparedStatementSetter.doSetValue(ArgumentPreparedStatementSetter.java:69)ntat org.springframework.jdbc.core.ArgumentPreparedStatementSetter.setValues(ArgumentPreparedStatementSetter.java:50)ntat org.springframework.jdbc.core.JdbcTemplate.lambda$update$2(JdbcTemplate.java:963)ntat org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:651)ntat org.springframework.jdbc.core.JdbcTemplate.update(JdbcTemplate.java:960)ntat org.springframework.jdbc.core.JdbcTemplate.update(JdbcTemplate.java:1015)ntat org.springframework.jdbc.core.JdbcTemplate.update(JdbcTemplate.java:1025)

And also the query itself (please understand the sql dialect mistakes and everything which may look odd, because the code comes from a commercial project):

UPDATE <TABLE_NAME> SET revision=revision + 1, column2 = ?, column3 = ?, ... WHERE id = ? , [null, <value2>, <value3>, ...]

I can also provide you a version in which everything worked perfectly fine, before upgrading the sqlite library -> 3.32.3.2

**Environment (please complete the following information):**
 - OS: macOS Ventura
 - CPU architecture: M1 Pro (arm64)
 - sqlite-jdbc version 3.41.2.2 & 3.42.0.0

**Comment by dbelob** [comment] 2023-08-23 13:00
**Describe the bug**
`NullPointerException` for `org.sqlite.jdbc3.JDBC3PreparedStatement.getParameterType` when no parameter has been set yet.

**To Reproduce**
Examples to reproduce error: see [sqlite-jdbc-first-null-error](https://github.com/dbelob/sqlite-jdbc-first-null-error) repository.

There ara two classes:
1. `JdbcTemplateTest` contains tests when used _Spring_ _JdbcTemplate_ methods
2. `PreparedStatementTest` contains tests when used _JDBC_ _PreparedStatement_ methods

In both cases `updateWithFirstNull` test fails with `NullPointerException` since _SQLite JDBC_ 3.41.2.2

Error reproduction for _Spring_ _JdbcTemplate_ (see `JdbcTemplateTest.updateWithFirstNull` method):
```
    @Test
    void updateWithFirstNull() {
        // NullPointerException since SQLite JDBC 3.41.2.2
        int count = jdbcTemplate.update("update test_table set first_field = ?, second_field = ?", null, "text 2");

        assertEquals(1, count);
    }
```

Error reproduction for _JDBC_ _PreparedStatement_ (see `PreparedStatementTest.updateWithFirstNull` method):
```
    @Test
    void updateWithFirstNull() throws SQLException {
        stat.executeUpdate("create table if not exists test_table(first_field integer, second_field text)");
        stat.executeUpdate("insert into test_table (first_field, second_field) values (1, 'text 1')");

        try (PreparedStatement ps = conn.prepareStatement("update test_table set first_field = ?, second_field = ?")) {
            // NullPointerException since SQLite JDBC 3.41.2.2
            assertThrows(SQLException.class, () -> ps.getParameterMetaData().getParameterType(1));
        }
    }
```

**Expected behavior**
`SQLException` should be thrown instead `NullPointerException`.

**Environment (please complete the following information):**
 - OS: all
 - CPU architecture: x86_64, arm64
 - sqlite-jdbc version 3.41.2.2, 3.42.0.0 (since 3.41.2.2)

**Additional context**
Error appeared after issue #882 and fixed by issue #911 (PR #912).
Fix should be included in the next release after 3.42.0.0 (according to the commits).

**Don't need to do anything, it's a duplicate issue #911**

**Comment by dbelob** [comment] 2023-08-23 13:36
@razvanmihaescu please check that the next version will fix your issue:
1. Clone SQLite JDBC repository: `git clone https://github.com/xerial/sqlite-jdbc.git`
2. Change directory: `cd sqlite-jdbc`
3. Build and install current unreleased version to local Maven repository: `mvn clean install`
4. Change version of `org.xerial:sqlite-jdbc` artifact to 3.42.0.1-SNAPSHOT in `pom.xml` of your application
5. Run your application: the error should disappear

**Comment by gotson** [comment] 2023-08-23 13:47
> @razvanmihaescu please check that the next version will fix your issue:
> 
> 1. Clone SQLite JDBC repository: `git clone https://github.com/xerial/sqlite-jdbc.git`
> 2. Change directory: `cd sqlite-jdbc`
> 3. Build and install current unreleased version to local Maven repository: `mvn clean install`
> 4. Change version of `org.xerial:sqlite-jdbc` artifact to 3.42.0.1-SNAPSHOT in `pom.xml` of your application
> 5. Run your application: the error should disappear

Or use the snapshot from maven snapshots.

**Comment by gotson** [comment] 2023-08-25 08:16
@razvanmihaescu please try the latest release 3.42.0.1

**Closed** 2023-10-24 10:56 UTC
Labels: waiting for feedback
