### ISSUE TITLE
 [SQLITE_BUSY]  The database file is locked in  MS Azure App Service

### ISSUE THREAD

**Issue by mica83** [xerial/sqlite-jdbc#759] opened 2022-08-08 10:52 UTC
Hello,

I have an app written in java with SpringBoot Framework. 
I'm Using JPA with sqlite-jdbc v. 3.36.0.3.

This is my application.prop file
#Driver name
spring.datasource.driver-class-name=org.sqlite.JDBC
#Database address
spring.datasource.url=jdbc:sqlite:@jdbc.url@
#Display database operation records
spring.jpa.show-sql=false

The app is deployed in MS Azure App Service and i have crated a Storage Account / File Share where i putted the database file. 

The problem is that when i try to send data (trough api) the app can't write to database for this reason:

`g.hibernate.resource.transaction.backend.jdbc.internal.JdbcResourceLocalTransactionCoordinatorImpl$TransactionDriverControlImpl.commit(JdbcResourceLocalTransactionCoordinatorImpl.java:282)
2022-08-08T10:46:25.397641190Z: [INFO]  	at org.hibernate.engine.transaction.internal.TransactionImpl.commit(TransactionImpl.java:101)
2022-08-08T10:46:25.397645590Z: [INFO]  	at org.springframework.orm.jpa.JpaTransactionManager.doCommit(JpaTransactionManager.java:534)
2022-08-08T10:46:25.397649990Z: [INFO]  	... 121 common frames omitted
2022-08-08T10:46:25.397654390Z: [INFO]  Caused by: org.sqlite.SQLiteException: [SQLITE_BUSY]  The database file is locked (database is locked)
2022-08-08T10:46:25.397659190Z: [INFO]  	at org.sqlite.core.DB.newSQLException(DB.java:1030)
2022-08-08T10:46:25.397676491Z: [INFO]  	at org.sqlite.core.DB.newSQLException(DB.java:1042)
2022-08-08T10:46:25.397680791Z: [INFO]  	at org.sqlite.core.DB.throwex(DB.java:1007)
2022-08-08T10:46:25.397685091Z: [INFO]  	at org.sqlite.core.DB.exec(DB.java:178)
2022-08-08T10:46:25.397689291Z: [INFO]  	at org.sqlite.SQLiteConnection.commit(SQLiteConnection.java:421)
2022-08-08T10:46:25.397693592Z: [INFO]  	at com.zaxxer.hikari.pool.ProxyConnection.commit(ProxyConnection.java:387)
2022-08-08T10:46:25.397697892Z: [INFO]  	at com.zaxxer.hikari.pool.HikariProxyConnection.commit(HikariProxyConnection.java)
2022-08-08T10:46:25.397715492Z: [INFO]  	at org.hibernate.resource.jdbc.internal.AbstractLogicalConnectionImplementor.commit(AbstractLogicalConnectionImplementor.java:86)
2022-08-08T10:46:25.397720192Z: [INFO]  	... 124 common frames omitted`

I think that could be different causes:

-The connection still open (i'm not managing the connection)
-MS Azure lock files in read only.

NB: Locally all works fine

Any ideas to resolve this issue? 

Thanks.

**Comment by johannespostler** [comment] 2022-08-08 14:15
Hi Michele,
We have the same issue and tried to fix it in this PR:

https://github.com/xerial/sqlite-jdbc/pull/432

Maybe @martinhaeusler can provide you with our JAR for testing.

**Comment by MartinHaeusler** [comment] 2022-08-08 14:22
@mica83 I would strongly advise against using SQLite with JPA. `SQLITE_BUSY` can be mitigated (at the cost of concurrency; see our PR) but never fully removed.

**Comment by mica83** [comment] 2022-08-08 14:29
Thank you Guys, i see the problem. But why yours PR not was merged?

**Comment by gotson** [comment] 2022-08-08 19:16
Duplicate of #90 

> Thank you Guys, i see the problem. But why yours PR not was merged?

The repo has been dormant for some time, I'm now maintaining it but that PR has conflicts that needs to be resolved. Once resolved I'll review it and it should be merged soon.

**Closed by gotson** 2022-08-08 19:16 UTC
