### ISSUE TITLE
Regexp support

### ISSUE THREAD

**Issue by icegood** [xerial/sqlite-jdbc#429] opened 2019-05-26 14:14 UTC
Seems issue #60  was incorrectly closed. The reason is that you may compile SQLite with regexp support. For example, you may use icu library. For this reason i want driver to correctly read sqlite engine settings and try to apply regexp operator whenever possible.

**Comment by gotson** [comment] 2021-07-23 11:11
You need to create user defined functions to support the `REGEXP` operator.

**Comment by gotson** [comment] 2021-07-25 10:01
```java
// Create regexp() function to make the REGEXP operator available
Function.create(connection, "REGEXP", new Function() {
  @Override
  protected void xFunc() throws SQLException {
    String expression = value_text(0);
    String value = value_text(1);
    if (value == null)
      value = "";

    Pattern pattern=Pattern.compile(expression);
    result(pattern.matcher(value).find() ? 1 : 0);
  }
});
```

[Source](https://stackoverflow.com/a/28587200/2041863)

**Comment by AhmedIbrahim12** [comment] 2021-10-05 00:35
> ```java
> // Create regexp() function to make the REGEXP operator available
> Function.create(connection, "REGEXP", new Function() {
>   @Override
>   protected void xFunc() throws SQLException {
>     String expression = value_text(0);
>     String value = value_text(1);
>     if (value == null)
>       value = "";
> 
>     Pattern pattern=Pattern.compile(expression);
>     result(pattern.matcher(value).find() ? 1 : 0);
>   }
> });
> ```
> 
> [Source](https://stackoverflow.com/a/28587200/2041863)

should this be added in the dialect? @gotson

**Comment by gotson** [comment] 2021-10-05 00:49
No, this should be part of your code. See examples of user defined functions [here](https://github.com/xerial/sqlite-jdbc/blob/3d04d7df0c89240add2c92189adb30b6cb7e6ae0/src/test/java/org/sqlite/UDFTest.java). You can use the same thing, but create a function with the special `REGEXP` name.

**Comment by AhmedIbrahim12** [comment] 2021-10-05 12:07
@gotson yes i figured that part, the problem is i want to register REGEXP to be used in JPA repository query or with entity manager context instead of  using the standard jdbc way, am i missing out on something?

**Comment by gotson** [comment] 2022-07-28 08:20
Seems the question was answered, i'm closing this. Comment if necessary.

**Closed by gotson** 2022-07-28 08:20 UTC
