### ISSUE TITLE
Cant retrieve multiple result sets from PreparedStatement.execute()

### ISSUE THREAD

**Issue by urosjarc** [xerial/sqlite-jdbc#1062] opened 2024-02-04 20:56 UTC
**Describe the bug**

If I run multiple queries per prepared statement...
```kotlin
val sql = """
    select * from Table1;
    select * from Table2;
    select * from Table3;
"""
```

And try to retrieve first 2 results I get only first result set per prepared statement.
PS: **This code works on postgresql driver and mariadb driver...**

```kotlin
ps = conn.prepareStatement(sql)
var isResultSet = ps.execute()

var count = 0
do {
    if (isResultSet) {
        rs = ps.resultSet
        returned.add(decodeResultSet(count, rs)) // decodeResultSet extracts informations from result set to objects
        rs.close()
    } else {
        if (ps.updateCount == -1) break
    } //If there is no more result finish

    count++
    isResultSet = ps.moreResults //Get next result
} while (isResultSet)

return returned
```

**Expected behavior**

The result set should get more results not only 1.

**Environment (please complete the following information):**
 - OS: linux ubuntu
 - CPU architecture: 64bit
 - sqlite-jdbc version 3.44.1.0

**Comment by gotson** [comment] 2024-02-05 01:58
Yes, this is a known limitation.

**Comment by gotson** [comment] 2024-02-05 01:58
Duplicate of #277

**Closed by gotson** 2024-02-05 01:58 UTC
Labels: triage

**Comment by urosjarc** [comment] 2024-02-05 06:16
Can you elaborate about this issue, I would really like to know more because I'm producing db library supporting 
many of known JDBC supported databases and some drivers have supported this, some not...

I would be more than happy if you provide some links related to this for further reading.

**Comment by gotson** [comment] 2024-02-05 06:23
did you read #277 ? it has all the info

**Comment by urosjarc** [comment] 2024-02-05 06:35
Yes I did... But I wonder if there is more informations related to this?

**Comment by gotson** [comment] 2024-02-05 06:56
No
