### ISSUE TITLE
broken downloads page link

### ISSUE THREAD

**Issue by Vandivier** [xerial/sqlite-jdbc#585] opened 2021-02-15 19:25 UTC
downloads page link in README.md under `https://github.com/xerial/sqlite-jdbc#download` links to a bitbucket url which displays "that link has now power here"

**Comment by T-Berger** [comment] 2022-01-18 09:45
It still isn't fixed get nowe:

Repository not found
The requested repository either does not exist or you do not have access. If you believe this repository exists and you have access, make sure you're authenticated.

**Comment by gotson** [comment] 2022-07-27 08:10
Duplicate of #544

**Closed by gotson** 2022-07-27 08:10 UTC
