### ISSUE TITLE
no native library for os.name=Linux and os.arch=ppc64le

### ISSUE THREAD

**Issue by shenhuicc** [xerial/sqlite-jdbc#450] opened 2019-09-06 05:33 UTC
when start the app on a IBM power9 server with centos 7.6,  an error occurs like:

no native library is found for os.name=Linux and os.arch=ppc64le

please see the attached picture
![sqlite-jdbc-native-error](https://user-images.githubusercontent.com/54973150/64403204-47417280-d0aa-11e9-971c-968d28d2f856.jpg)

I see the newest jar ball has already include os.name=Linux and os.arch=ppc64 under the path "sqlite-jdbc/org/sqlite/native/Linux",  but miss a "ppc64le" directory.

maybe just make a directory called "ppc64le", then copy the lib file from "ppc64" directory to "ppc64le" directory. will this works ?

**Comment by rashmi-ibm** [comment] 2019-09-12 06:34
I am too facing a similar issue on power with the below error. Any details when the above PR would be merged.

Caused by: java.lang.Exception: No native library is found for os.name=Linux and os.arch=ppc64le. path=/org/sqlite/native/Linux/ppc64le
    	at org.sqlite.SQLiteJDBCLoader.loadSQLiteNativeLibrary(SQLiteJDBCLoader.java:333) ~[sqlite-jdbc-3.28.0.jar:?]
    	at org.sqlite.SQLiteJDBCLoader.initialize(SQLiteJDBCLoader.java:64) ~[sqlite-jdbc-3.28.0.jar:?]
    	at org.sqlite.core.NativeDB.load(NativeDB.java:63) ~[sqlite-jdbc-3.28.0.jar:?]
    	at org.sqlite.SQLiteConnection.open(SQLiteConnection.java:235) ~[sqlite-jdbc-3.28.0.jar:?]

**Comment by shenhuicc** [comment] 2019-09-12 06:43
hi, rashmi-ibm :
 
I just make a directory "ppc64le " and copy the libsqlitejdbc.so under the directory "ppc64"  to "ppc64le".
 
It works.
 
you could try and test your app to see if all functions are correct.
 
----- Original message -----From: rashmi-ibm <notifications@github.com>To: xerial/sqlite-jdbc <sqlite-jdbc@noreply.github.com>Cc: shenhuicc <shenhnj@cn.ibm.com>, Author <author@noreply.github.com>Subject: [EXTERNAL] Re: [xerial/sqlite-jdbc] no native library for os.name=Linux and os.arch=ppc64le (#450)Date: Thu, Sep 12, 2019 2:34 PM 
I am too facing a similar issue on power with the below error. Any details when the above PR would be merged.
Caused by: java.lang.Exception: No native library is found for os.name=Linux and os.arch=ppc64le. path=/org/sqlite/native/Linux/ppc64leat org.sqlite.SQLiteJDBCLoader.loadSQLiteNativeLibrary(SQLiteJDBCLoader.java:333) ~[sqlite-jdbc-3.28.0.jar:?]at org.sqlite.SQLiteJDBCLoader.initialize(SQLiteJDBCLoader.java:64) ~[sqlite-jdbc-3.28.0.jar:?]at org.sqlite.core.NativeDB.load(NativeDB.java:63) ~[sqlite-jdbc-3.28.0.jar:?]at org.sqlite.SQLiteConnection.open(SQLiteConnection.java:235) ~[sqlite-jdbc-3.28.0.jar:?]

**Comment by shenhuicc** [comment] 2019-09-12 06:48
if you want to build it on ppc64le , reference to this link:
 
 
Add linux ppc64 binary     https://g2.gitblit.com/xerial/sqlite-jdbc/commit/48479d1f7afd608c5701cd705acd794cd7949e40
 
----- Original message -----From: rashmi-ibm <notifications@github.com>To: xerial/sqlite-jdbc <sqlite-jdbc@noreply.github.com>Cc: shenhuicc <shenhnj@cn.ibm.com>, Author <author@noreply.github.com>Subject: [EXTERNAL] Re: [xerial/sqlite-jdbc] no native library for os.name=Linux and os.arch=ppc64le (#450)Date: Thu, Sep 12, 2019 2:34 PM 
I am too facing a similar issue on power with the below error. Any details when the above PR would be merged.
Caused by: java.lang.Exception: No native library is found for os.name=Linux and os.arch=ppc64le. path=/org/sqlite/native/Linux/ppc64leat org.sqlite.SQLiteJDBCLoader.loadSQLiteNativeLibrary(SQLiteJDBCLoader.java:333) ~[sqlite-jdbc-3.28.0.jar:?]at org.sqlite.SQLiteJDBCLoader.initialize(SQLiteJDBCLoader.java:64) ~[sqlite-jdbc-3.28.0.jar:?]at org.sqlite.core.NativeDB.load(NativeDB.java:63) ~[sqlite-jdbc-3.28.0.jar:?]at org.sqlite.SQLiteConnection.open(SQLiteConnection.java:235) ~[sqlite-jdbc-3.28.0.jar:?]

**Comment by rashmi-ibm** [comment] 2019-09-12 07:10
I am building a project which has a gradle dependency added for sqllite-jdbc as shown below. I would need the published/fixed jar for my issue resolution.

implementation group: 'org.xerial', name: 'sqlite-jdbc', version: '3.15.1'

**Comment by shenhuicc** [comment] 2019-09-12 07:22
try:
 
1. download sqlite-jdbc 3.15.1 source code
 
     https://github.com/xerial/sqlite-jdbc
 
2.  modify the Makefile and Makefile.common  according to the link 
 
      https://g2.gitblit.com/xerial/sqlite-jdbc/commit/48479d1f7afd608c5701cd705acd794cd7949e40
 
       remember to change all "ppc64" to "ppc64le"
 
3. compile  with maven "mvn compile"
 
4. it should generate libsqlitejdbc.so if all goes well
 
 
 
----- Original message -----From: rashmi-ibm <notifications@github.com>To: xerial/sqlite-jdbc <sqlite-jdbc@noreply.github.com>Cc: shenhuicc <shenhnj@cn.ibm.com>, Author <author@noreply.github.com>Subject: [EXTERNAL] Re: [xerial/sqlite-jdbc] no native library for os.name=Linux and os.arch=ppc64le (#450)Date: Thu, Sep 12, 2019 3:10 PM 
I am building a project which has a gradle dependency added for sqllite-jdbc as shown below. I would need the published/fixed jar for my issue resolution.
implementation group: 'org.xerial', name: 'sqlite-jdbc', version: '3.15.1'

**Closed** 2022-07-28 14:00 UTC
Labels: enhancement
