### ISSUE TITLE
Version 3.43.0.0 fails on statement.getGeneratedKeys()

### ISSUE THREAD

**Issue by sproket** [xerial/sqlite-jdbc#965] opened 2023-09-04 09:47 UTC
**Describe the bug**
Running some code to insert and return a generated key with sqlite jdbc version 3.36.0.2 works fine. Once I update to version 3.43.0.0 I get the following exception:

net.sf.persism.PersismException: not implemented by SQLite JDBC driver

Caused by: java.sql.SQLFeatureNotSupportedException: not implemented by SQLite JDBC driver
	at org.sqlite.jdbc3.JDBC3PreparedStatement.unsupported(JDBC3PreparedStatement.java:448)
	at org.sqlite.jdbc3.JDBC3Statement.getGeneratedKeys(JDBC3Statement.java:357)
	at sproket.github.io.persism/net.sf.persism.Session.insert(Session.java:681)

When I'm calling: 

 rs = st.getGeneratedKeys();

**To Reproduce**
To reproduce perform and insert and try to get the new autoinc from the statement object.

**Expected behavior**
It should insert and return the auto-inc value.

**Logs**
see above

**Environment (please complete the following information):**
 - OS: Windows 11
 - CPU architecture: ?
 - sqlite-jdbc version 3.43.0.0
 - Java version openjdk 17,0.4.1

**Comment by gotson** [comment] 2023-09-04 09:59
Duplicate of #963 (which is pinned at the top)

**Closed by gotson** 2023-09-04 09:59 UTC
Labels: triage

**Comment by prrvchr** [comment] 2024-02-08 20:52
@sproket  You can try this version: [SQLite-jdbc-3.45.1.3-SNAPSHOT.jar](https://github.com/prrvchr/sqlite-jdbc/releases/download/3.45.1.3-SNAPSHOT/sqlite-jdbc-3.45.1.3-SNAPSHOT.jar) normally it is full compatible with JDBC 4.1and therefore able to recover the primary keys via JDBC.
