### ISSUE TITLE
java.lang.UnsatisfiedLinkError: org.sqlite.core.NativeDB._open(Ljava/lang/String;I)V

### ISSUE THREAD

**Issue by manjunathshetty** [xerial/sqlite-jdbc#97] opened 2016-03-08 06:16 UTC
I am getting this error only in . **Sqlite JDBC version 3.8.11.2**

> Windows Server 2012 R2

```
javax.persistence.PersistenceException: java.lang.UnsatisfiedLinkError: org.sqlite.core.NativeDB._open(Ljava/lang/String;I)V
    at org.eclipse.persistence.internal.jpa.EntityManagerSetupImpl.deploy(EntityManagerSetupImpl.java:815)
    at org.eclipse.persistence.internal.jpa.EntityManagerFactoryDelegate.getAbstractSession(EntityManagerFactoryDelegate.java:205)
    at org.eclipse.persistence.internal.jpa.EntityManagerFactoryDelegate.createEntityManagerImpl(EntityManagerFactoryDelegate.java:305)
    at org.eclipse.persistence.internal.jpa.EntityManagerFactoryImpl.createEntityManagerImpl(EntityManagerFactoryImpl.java:337)
    at org.eclipse.persistence.internal.jpa.EntityManagerFactoryImpl.createEntityManager(EntityManagerFactoryImpl.java:303)
    at com.accelerite.radialive.cs.storage.dao.ClusterPropertiesDAO.getPropertyByTypeAndKeyWithSubType(ClusterPropertiesDAO.java:42)
    at com.accelerite.radialive.cs.storage.dao.ClusterPropertiesDAO.addClusterProperty(ClusterPropertiesDAO.java:149)
    at com.accelerite.radialive.cs.util.Bootstrap.contextInitialized(Bootstrap.java:56)
    at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:5003)
    at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5517)
    at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
    at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:901)
    at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:877)
    at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:652)
    at org.apache.catalina.startup.HostConfig.deployWAR(HostConfig.java:1095)
    at org.apache.catalina.startup.HostConfig$DeployWar.run(HostConfig.java:1930)
    at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
    at java.util.concurrent.FutureTask.run(Unknown Source)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
    at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.UnsatisfiedLinkError: org.sqlite.core.NativeDB._open(Ljava/lang/String;I)V
    at org.sqlite.core.NativeDB._open(Native Method)
    at org.sqlite.core.DB.open(DB.java:161)
    at org.sqlite.core.CoreConnection.open(CoreConnection.java:220)
    at org.sqlite.core.CoreConnection.<init>(CoreConnection.java:76)
    at org.sqlite.jdbc3.JDBC3Connection.<init>(JDBC3Connection.java:24)
    at org.sqlite.jdbc4.JDBC4Connection.<init>(JDBC4Connection.java:23)
    at org.sqlite.SQLiteConnection.<init>(SQLiteConnection.java:45)
    at org.sqlite.JDBC.createConnection(JDBC.java:114)
    at org.sqlite.JDBC.connect(JDBC.java:88)
    at java.sql.DriverManager.getConnection(Unknown Source)
    at java.sql.DriverManager.getConnection(Unknown Source)
    at org.eclipse.persistence.sessions.DefaultConnector.connect(DefaultConnector.java:98)
    at org.eclipse.persistence.sessions.DatasourceLogin.connectToDatasource(DatasourceLogin.java:162)
    at org.eclipse.persistence.internal.sessions.DatabaseSessionImpl.setOrDetectDatasource(DatabaseSessionImpl.java:207)
    at org.eclipse.persistence.internal.sessions.DatabaseSessionImpl.loginAndDetectDatasource(DatabaseSessionImpl.java:760)
    at org.eclipse.persistence.internal.jpa.EntityManagerFactoryProvider.login(EntityManagerFactoryProvider.java:265)
    at org.eclipse.persistence.internal.jpa.EntityManagerSetupImpl.deploy(EntityManagerSetupImpl.java:731)
    ... 20 more
```

**Comment by msferry** [comment] 2016-03-14 22:26
I'm getting the same error on ubuntu linux 14.04 running on a pandaboard (armhf architecture):

03/14/2016 14:59:31: Caused by: java.lang.UnsatisfiedLinkError: org.sqlite.core.NativeDB._open(Ljava/lang/String;I)V
03/14/2016 14:59:31:    at org.sqlite.core.NativeDB._open(Native Method)
03/14/2016 14:59:31:    at org.sqlite.core.DB.open(DB.java:161)
03/14/2016 14:59:31:    at org.sqlite.core.CoreConnection.open(CoreConnection.java:220)
03/14/2016 14:59:31:    at org.sqlite.core.CoreConnection.<init>(CoreConnection.java:76)
03/14/2016 14:59:31:    at org.sqlite.jdbc3.JDBC3Connection.<init>(JDBC3Connection.java:24)
03/14/2016 14:59:31:    at org.sqlite.jdbc4.JDBC4Connection.<init>(JDBC4Connection.java:23)
03/14/2016 14:59:31:    at org.sqlite.SQLiteConnection.<init>(SQLiteConnection.java:45)
03/14/2016 14:59:31:    at org.sqlite.JDBC.createConnection(JDBC.java:114)
03/14/2016 14:59:31:    at org.sqlite.JDBC.connect(JDBC.java:88)
03/14/2016 14:59:31:    at java.sql.DriverManager.getConnection(DriverManager.java:571)
03/14/2016 14:59:31:    at java.sql.DriverManager.getConnection(DriverManager.java:233)

**Comment by mhdr** [comment] 2016-03-30 07:56
I have the same problem on Raspbian 2016

**Comment by zh32** [comment] 2016-04-16 09:59
Same on Debian 8

**Comment by jesudornenkrone** [comment] 2016-04-25 09:57
Windows 10 Pro works fine, however Windows Server 2012 does not

Also using Sqlite JDBC version 3.8.11.2

**Comment by jesudornenkrone** [comment] 2016-04-25 15:50
Okay, at least I found my problem: The tmp directory for the application was wrong.

I now added a check to my application, whether the tmp directory exists, is a directory and can be written. Hope that helps me realize the problem sooner next time.

**Comment by awaters1** [comment] 2016-05-22 20:42
For linux I was able to work around this by making sure the tmp directory had exec permissions.

**Comment by JitenderRaghuvanshi** [comment] 2016-07-20 07:08
Hi,

I am using SQLite version 3.8.11.2 and it's giving the same error (java.lang.UnsatisfiedLinkError: org.sqlite.core.NativeDB._open(Ljava/lang/String;I)V)
I tried other verions as well and 3.7.2 works fine on my system but with this version i face another issue. 
I am using DBCP2 for connection pooling and with SQLite 3.7.2 it gives following error.
java.lang.AbstractMethodError: org.sqlite.Conn.isValid(I)Z

It means isValid() method is not present in SQLite 3.7.2.  And the version where this method is available, is not working on my system. Right?

I am using window 10 pro. 
Same code runs fine on other Systems with WIndow 10 pro. Only my System is giving this issue. 
I would really appreciate any help on this issue. 

Thanks,
Jitender

**Comment by jesudornenkrone** [comment] 2016-07-20 09:50
Please check, that the tmpDir is set and you have the permissions. The SQLite DLL gets extracted from the jar to the tmp.

`final File tmp = new File(System.getProperty("java.io.tmpdir"));
if (!tmp.exists() || !tmp.isDirectory() || !tmp.canRead() || !tmp.canWrite()) {
    throw new Exception("error with tmpDir");
}
SQLiteJDBCLoader.initialize();`

**Comment by JitenderRaghuvanshi** [comment] 2016-07-20 10:24
Hey jesudornenkrone

I used the code snippet and got following exception.

`2016-07-20 15:50:58 ERROR DvSearchServices:152 - error with tmpDir
java.lang.Exception: error with tmpDir
	at com.dataprivc.searchengine.consumer.DvSearchTaskServicesImpl.getSqliteDSConn(DvSearchTaskServicesImpl.java:158)
	at com.dataprivc.searchengine.consumer.DvSearchTaskServicesImpl.getTaskStatus(DvSearchTaskServicesImpl.java:37)
	at com.dataprivc.searchengine.webservices.DvSearchServices.getStatus(DvSearchServices.java:147)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.sun.jersey.spi.container.JavaMethodInvokerFactory$1.invoke(JavaMethodInvokerFactory.java:60)
	at com.sun.jersey.server.impl.model.method.dispatch.AbstractResourceMethodDispatchProvider$ResponseOutInvoker._dispatch(AbstractResourceMethodDispatchProvider.java:205)
	at com.sun.jersey.server.impl.model.method.dispatch.ResourceJavaMethodDispatcher.dispatch(ResourceJavaMethodDispatcher.java:75)
	at com.sun.jersey.server.impl.uri.rules.HttpMethodRule.accept(HttpMethodRule.java:302)
	at com.sun.jersey.server.impl.uri.rules.RightHandPathRule.accept(RightHandPathRule.java:147)
	at com.sun.jersey.server.impl.uri.rules.ResourceClassRule.accept(ResourceClassRule.java:108)
	at com.sun.jersey.server.impl.uri.rules.RightHandPathRule.accept(RightHandPathRule.java:147)
	at com.sun.jersey.server.impl.uri.rules.RootResourceClassesRule.accept(RootResourceClassesRule.java:84)
	at com.sun.jersey.server.impl.application.WebApplicationImpl._handleRequest(WebApplicationImpl.java:1542)
	at com.sun.jersey.server.impl.application.WebApplicationImpl._handleRequest(WebApplicationImpl.java:1473)
	at com.sun.jersey.server.impl.application.WebApplicationImpl.handleRequest(WebApplicationImpl.java:1419)
	at com.sun.jersey.server.impl.application.WebApplicationImpl.handleRequest(WebApplicationImpl.java:1409)
	at com.sun.jersey.spi.container.servlet.WebComponent.service(WebComponent.java:409)
	at com.sun.jersey.spi.container.servlet.ServletContainer.service(ServletContainer.java:558)
	at com.sun.jersey.spi.container.servlet.ServletContainer.service(ServletContainer.java:733)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:731)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:220)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:122)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:505)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:169)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:103)
	at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:956)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:436)
	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1078)
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:625)
	at org.apache.tomcat.util.net.AprEndpoint$SocketProcessor.doRun(AprEndpoint.java:2517)
	at org.apache.tomcat.util.net.AprEndpoint$SocketProcessor.run(AprEndpoint.java:2506)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:745)
`

So the tmpdir does not exist. How do I fix this?

**Comment by JitenderRaghuvanshi** [comment] 2016-07-20 10:56
Hey jesudornenkrone,

Thanks for pointing in the right direction. 
I printed the path of the temp file and it was right in the Tomcat server's home directory. And there wa no temp folder. 
I created a folder there manually and it worked like a charm. Now i can add a check in my code that if temp directory doesn't exist then create one. 

Thanks a lot Again

**Comment by 2bdenny** [comment] 2016-09-05 13:26
Same error as above.
The root cause of my error is that: THERE IS NO TEMP FOLDER IN TOMCAT INSTALL DIR
So My solution:
cd /usr/share/tomcat8 # this is the install dir of my tomcat8 (cause I install it by apt-get)
sudo mkdir temp
sudo chmod 777 temp/
Then restart tomcat, the error is gone.

**Comment by sfbell09** [comment] 2016-10-05 17:54
One other thing that could be causing this issue is that sqlite is only allowing a single network connection to the database. I was running into this error during development. If I republished the code in Eclipse and didn't stop and start the web application container (weblogic in this case) I would get this error. Stopping weblogic and starting it again worked to get sqlite to respond again.

**Comment by kengle** [comment] 2016-10-09 02:00
same error, version 3.14.2,
`uname -a`
`Linux AY14011115535187549fZ 3.2.0-29-generic #46-Ubuntu SMP Fri Jul 27 17:03:23 UTC 2012 x86_64 x86_64 x86_64 GNU/Linux`

`lscpu`

> Architecture:          x86_64
CPU op-mode(s):        32-bit, 64-bit
Byte Order:            Little Endian
CPU(s):                4
On-line CPU(s) list:   0-3
Thread(s) per core:    1
Core(s) per socket:    4
Socket(s):             1
NUMA node(s):          1
Vendor ID:             GenuineIntel
CPU family:            6
Model:                 45
Stepping:              7
CPU MHz:               2200.062
BogoMIPS:              4391.09
Hypervisor vendor:     Xen
Virtualization type:   full
L1d cache:             32K
L1i cache:             32K
L2 cache:              256K
L3 cache:              15360K
NUMA node0 CPU(s):     0-3

**Comment by camsaul** [comment] 2016-11-15 19:55
I've seen a few people run into this error too with version `3.14.2.1`. Weirdly enough it didn't happen with version `3.8.11.2`.

**Comment by BlackVampire** [comment] 2016-12-07 17:30
I only recently downloaded the source code, compiled it and tried to include in into my java application (console based server application with SQLite support planned).
The compiled  shared object in included in package /org/sqlite/native/Linux/arm and is named libsqlitejdbc.so

Now, according to some posts here, which I found useful, my server application checks "java.io.tmpdir" for correct permissions. Everything seems to be OK.

The error happens to me if my server is being executed on a Raspberry Pi 3 and the following line is executed:

**Comment by Huntr0** [comment] 2016-12-10 15:30
I had the problem with Arch Linux.
My tmp directory was mounted with `noexec` option. Allowing execution solved the problem for me.

**Comment by xerial** [comment] 2017-01-06 23:33
I think #191 can solve this permission problem.`org.sqlite.tmpdir` JVM env can be used to specify the temporary folder.

The latest version with this support is available from here:
https://oss.sonatype.org/content/repositories/snapshots/org/xerial/sqlite-jdbc/3.16.1-SNAPSHOT/sqlite-jdbc-3.16.1-20170106.232609-17.jar

**Comment by xerial** [comment] 2017-01-06 23:33
Let me close this ticket.

**Closed by xerial** 2017-01-06 23:33 UTC

**Comment by rustyx** [comment] 2018-10-12 08:47
Check that your **`/tmp`** is not mounted **`noexec`**. Debian 9, for example, mounts `/tmp` with `noexec`.

```
$ mount | grep /tmp
/dev/sda6 on /tmp type ext4 (rw,noexec,nosuid,nodev,relatime,data=ordered)
```

If this is the case, there are 2 workarounds:

**Solution 1.** Edit `/etc/fstab` and remove `noexec` from `/tmp`. Then remount `/tmp`:

```
$ mount -o remount /tmp
```

**Solution 2.** Use another `tmp` location.
```
$ java ... -Djava.io.tmpdir=/var/run/some-other-location
```

If running **`tomcat8`** on Debian, edit `/etc/default/tomcat8` and add:
```
JVM_TMP=$CATALINA_BASE/temp
```

**Comment by jrodri0790** [comment] 2019-09-20 14:42
how to solve it on mac???
