### ISSUE TITLE
Unable to acquire a JDBC connection with a local temp file

### ISSUE THREAD

**Issue by krishnanand** [xerial/sqlite-jdbc#139] opened 2016-07-21 01:11 UTC
I apologize if this has been addressed before. I could not find any resolution to my problem in spite of [asking on StackOverflow](http://stackoverflow.com/questions/38409036/unable-to-connect-to-sqlite-file-on-disk).

I am hoping that someone can help. My usecase is given below:
1. I upload the SQLite local db file to a web app. This is automatically converted into a multipart file from which I need to extract the content.
2. Because this is a multipart file, I have access to the byte array, which is passed to the function.
3. Write the byte array to a local temp file.
4. Create a connection to make JDBC calls.

My stack trace on a Windows machine:

```
com.mycompany.cms.tools.dao.ContentRetrievalException: Unable to retrieve content for Unable to parse file : cms4275726046178009363.db
    at com.mycompany.cms.tools.service.CmsContentServiceImpl.readContentFromSqliteStream(CmsContentServiceImpl.java:156)
    at com.mycompany.cms.tools.service.CmsContentServiceImplTest.testReadContentFromSqliteStream(CmsContentServiceImplTest.java:75)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
    at org.testng.internal.MethodInvocationHelper$1.runTestMethod(MethodInvocationHelper.java:197)
    at org.springframework.test.context.testng.AbstractTestNGSpringContextTests.run(AbstractTestNGSpringContextTests.java:175)
    at org.testng.internal.MethodInvocationHelper.invokeHookable(MethodInvocationHelper.java:209)
    at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
    at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
    at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
    at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
    at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
    at org.testng.TestRunner.privateRun(TestRunner.java:782)
    at org.testng.TestRunner.run(TestRunner.java:632)
    at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
    at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
    at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
    at org.testng.SuiteRunner.run(SuiteRunner.java:268)
    at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
    at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
    at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
    at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
    at org.testng.TestNG.run(TestNG.java:1064)
    at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:126)
    at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:137)
    at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:58)
Caused by: java.sql.SQLException: No suitable driver found for jdbc:sqlite:C:\Users\zk5426x\AppData\Local\Temp\cms4275726046178009363.db
    at java.sql.DriverManager.getConnection(DriverManager.java:689)
    at java.sql.DriverManager.getConnection(DriverManager.java:270)
    at com.mycompany.cms.tools.dao.CmsLocalContentDao.readContentsFromResource(CmsLocalContentDao.java:45)
    ... 30 more
```

My code snippet:

```
public Set<CmsXServiceContent> readContentFromSqliteStream(byte[] bytes) throws Exception {
       Path path = null;
    try {
      path = Files.createTempFile("cms", ".db");
      path.toFile().setWritable(true);
      path.getParentFile().setWritable(true);
      if (LOGGER.isInfoEnabled()) {
        LOGGER.info("Temporary file created = " + path.toString());
      }
      try (ByteArrayInputStream is = new ByteArrayInputStream(bytes);) {
        Files.copy(is, path, StandardCopyOption.REPLACE_EXISTING);
        Class.forName("org.sqlite.JDBC");
     // This following statement throws an exception.
      try(
        Connection conn =
            DriverManager.getConnection(
                 "jdbc:sqlite:" +  path.toFile().getCanonicalPath());) {

        // Prepared Statements and result set query to return the appropriate output.
        }
      }
    } catch (Exception e) {
      LOGGER.error("Unable to create a temporary file: cms.db");
      throw e;
    } finally {
      if (path != null) {
        path.toFile().deleteOnExit();
      }
    }
}
```

My Maven configuration

```
<dependency>
    <groupId>org.xerial</groupId>
    <artifactId>sqlite-jdbc</artifactId>
    <version>3.8.7</version>
</dependency>
```

The output of the following statements are as follows

```
System.out.println(localFile.getPath());
System.out.println(localFile.getCanonicalPath());
System.out.println(localFile.getAbsolutePath());
System.out.println(localFile.getName());
```

is 

```
C:\Users\zk5426x\AppData\Local\Temp\cms7629729726748856652.db
C:\Users\zk5426x\AppData\Local\Temp\cms7629729726748856652.db
C:\Users\zk5426x\AppData\Local\Temp\cms7629729726748856652.db
cms7629729726748856652.db
```

I don't know what I am doing wrong. Any assistance would be appreciated.

**Comment by gitblit** [comment] 2016-07-22 13:57
Your approach looks fine but I can't help feeling that the shared
stacktrace is incomplete. I would expect to see an IOException or
SQLException. Or at least some explanation.

**Comment by krishnanand** [comment] 2016-07-22 20:00
I created a test case with Maven set up and I tried to print the stack trace with a different path this time. The stack trace is given below. The file "test.db" does not exist, and is sought to be created

```
java.sql.SQLException: No suitable driver found for jdbc:sqlite:src/test/resources/com/mycompany/cms/tools/service/test.db
	at java.sql.DriverManager.getConnection(DriverManager.java:689)
	at java.sql.DriverManager.getConnection(DriverManager.java:208)
	at com.mycompany.cms.tools.common.TestDataUtil.initializeSqliteConfiguration(TestDataUtil.java:96)
	at com.mycompany.cms.tools.service.CmsContentServiceImplTest.setUpOnce(CmsContentServiceImplTest.java:53)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:514)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:215)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:142)
	at org.testng.internal.TestMethodWorker.invokeBeforeClassMethods(TestMethodWorker.java:178)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:126)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:137)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:58)
```

**Comment by gitblit** [comment] 2016-07-23 01:38
In this particular case it appears the SQLite JDBC driver is not on the
test classpath. That is why no suitable driver is found.

**Comment by krishnanand** [comment] 2016-07-23 03:00
That is why I thought too.  But,  I checked Eclipse Java build path, and I was able to confirm that SQLite-jdbc jar is a part of classpath. I have attached a 
![SQLite classpath snapshot](https://cloud.githubusercontent.com/assets/1548607/17075391/bf0038d4-5046-11e6-81c3-3745ad88f038.png) for your perusal.

**Comment by krishnanand** [comment] 2016-07-26 21:19
I tried an alternate approach. I created a webapp that would trigger this block of code. I failed here as well.

My stacktrace is given below

```
java.sql.SQLException: No suitable driver found for jdbc:sqlite:C:/Downloads/apache-tomcat-8.0.36/temp/cms6423887946915236852.db

                at java.sql.DriverManager.getConnection(Unknown Source)

                at java.sql.DriverManager.getConnection(Unknown Source)

                at com.mycompany.cms.tools.dao.CmsLocalContentDao.readContentsFromResource(CmsLocalContentDao.java:52)

                at com.mycompany.cms.tools.dao.CmsLocalContentDao.readContentsFromResource(CmsLocalContentDao.java:25)

                at com.mycompany.cms.tools.service.CmsContentServiceImpl.readContentFromSqliteStream(CmsContentServiceImpl.java:157)

                at com.mycompany.cms.tools.service.XServiceDelegateImpl.generateMismatchedData(XServiceDelegateImpl.java:39)

                at com.mycompany.cms.tools.controller.CmsValidationController.generateCmsValidationReport(CmsValidationController.java:143)

                at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)

                at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)

                at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)

                at java.lang.reflect.Method.invoke(Unknown Source)

                at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:221)

                at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:136)

                at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:114)

                at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:827)

                at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:738)

                at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:85)

                at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:963)

                at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:897)

                at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:970)

                at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:872)

                at javax.servlet.http.HttpServlet.service(HttpServlet.java:648)

                at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:846)

                at javax.servlet.http.HttpServlet.service(HttpServlet.java:729)

                at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:292)

                at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)

                at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)

                at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240)

                at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)

                at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:212)

                at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:106)

                at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:502)

                at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:141)

                at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79)

                at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:616)

                at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:88)

                at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:528)

                at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1099)

                at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:670)

                at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1520)

                at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1476)

                at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)

                at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)

                at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)

                at java.lang.Thread.run(Unknown Source)
```

My jars set in WEB-INF/lib directory

![tomcat_webapp WEB-INF/lib directory path](https://cloud.githubusercontent.com/assets/1548607/17155895/de7b2c58-533b-11e6-92d0-a42d9cbdd509.png)

**Comment by dyorgio** [comment] 2016-08-14 03:33
Maybe a problem with classloaders... between sqlite classes and DriverManager.
Try to put sqlite jar on tomcat classpath (ext) and remove it from your application (like provided libs (servlet, jee, jsf, etc...).

**Comment by compengi** [comment] 2016-08-29 15:58
JDBC driver has to reside in **apache-tomcat-8.0.36/lib/** as suggested there https://github.com/xerial/sqlite-jdbc#using-sqlitejdbc-with-tomcat6-web-server

**Comment by sualeh** [comment] 2017-10-15 17:17
Closing, since this is not a bug or enhancement request. If the JDBC driver cannot be found, you need to look at the *runime* classpath, not the *build* classpath,

**Closed by sualeh** 2017-10-15 17:17 UTC
