### ISSUE TITLE
Are we ready to support getBlob

### ISSUE THREAD

**Issue by SpaceMiao** [xerial/sqlite-jdbc#1183] opened 2024-09-25 08:24 UTC
**Describe the bug**
I'm using Quartz as a scheduling middleware in SpringBoot project, but I found that it doesn't work very well with sqlite.
When I create a scheduled task, an error occurs in the program.
```java
org.quartz.JobPersistenceException: Couldn't acquire next trigger: Couldn't retrieve trigger: null
	at org.quartz.impl.jdbcjobstore.JobStoreSupport.acquireNextTrigger(JobStoreSupport.java:2923) ~[quartz-2.3.2.jar:na]
	at org.quartz.impl.jdbcjobstore.JobStoreSupport$41.execute(JobStoreSupport.java:2805) ~[quartz-2.3.2.jar:na]
	at org.quartz.impl.jdbcjobstore.JobStoreSupport$41.execute(JobStoreSupport.java:2803) ~[quartz-2.3.2.jar:na]
	at org.quartz.impl.jdbcjobstore.JobStoreSupport.executeInNonManagedTXLock(JobStoreSupport.java:3864) ~[quartz-2.3.2.jar:na]
	at org.quartz.impl.jdbcjobstore.JobStoreSupport.acquireNextTriggers(JobStoreSupport.java:2802) ~[quartz-2.3.2.jar:na]
	at org.quartz.core.QuartzSchedulerThread.run(QuartzSchedulerThread.java:287) ~[quartz-2.3.2.jar:na]
Caused by: org.quartz.JobPersistenceException: Couldn't retrieve trigger: null
	at org.quartz.impl.jdbcjobstore.JobStoreSupport.retrieveTrigger(JobStoreSupport.java:1538) ~[quartz-2.3.2.jar:na]
	at org.quartz.impl.jdbcjobstore.JobStoreSupport.acquireNextTrigger(JobStoreSupport.java:2854) ~[quartz-2.3.2.jar:na]
	... 5 common frames omitted
Caused by: java.sql.SQLFeatureNotSupportedException: null
	at org.sqlite.jdbc4.JDBC4ResultSet.unused(JDBC4ResultSet.java:347) ~[sqlite-jdbc-3.36.0.3.jar:na]
	at org.sqlite.jdbc4.JDBC4ResultSet.getBlob(JDBC4ResultSet.java:390) ~[sqlite-jdbc-3.36.0.3.jar:na]
	at com.alibaba.druid.pool.DruidPooledResultSet.getBlob(DruidPooledResultSet.java:1157) ~[druid-1.2.23.jar:na]
	at org.quartz.impl.jdbcjobstore.StdJDBCDelegate.getObjectFromBlob(StdJDBCDelegate.java:3190) ~[quartz-2.3.2.jar:na]
	at org.quartz.impl.jdbcjobstore.StdJDBCDelegate.selectTrigger(StdJDBCDelegate.java:1780) ~[quartz-2.3.2.jar:na]
	at org.quartz.impl.jdbcjobstore.JobStoreSupport.retrieveTrigger(JobStoreSupport.java:1536) ~[quartz-2.3.2.jar:na]
	... 6 common frames omitted
```
**To Reproduce**
Provide a sample code that reproduces the error.

Quartz.propertites
org.quartz.jobStore.driverDelegateClass=org.quartz.impl.jdbcjobstore.StdJDBCDelegate

```xml
        <dependency>
            <groupId>org.xerial</groupId>
            <artifactId>sqlite-jdbc</artifactId>
            <version>3.36.0.3</version>
        </dependency>
```
**Expected behavior**

**Logs**
If applicable, provide logs.

**Environment (please complete the following information):**
 - OS: [e.g. Windows 7]
 - CPU architecture: [e.g. x86_64, arm64]
 - sqlite-jdbc version: 3.36.0.3

**Additional context**

![image](https://github.com/user-attachments/assets/40aadd93-6d36-4e56-abce-9042a7f1a13b)

**Comment by gotson** [comment] 2024-09-25 09:54
Duplicate of #622

**Closed by gotson** 2024-09-25 09:54 UTC
Labels: triage
