### ISSUE TITLE
jdbc:sqlite Intellij 

### ISSUE THREAD

**Issue by DSkilton** [xerial/sqlite-jdbc#406] opened 2019-03-02 21:37 UTC
Evening,

I have scoured Stackoverflow and Oracle for the last two weeks but I cannot find solution and would really appreciate some help. This is the code I have so far (there is a copy on my repositorys called modus: 

```java
    public static void Connection() {

        final String connectionUrl = Password.getURL();

        try {

//            Class.forName("org.sqlite.JDBC");
            Connection con = DriverManager.getConnection(connectionUrl);
            System.out.println("Connected");
            //while(returnStatement.next()) {
            //System.out.println("rs.getString");
            //}

            } catch (SQLException e) {
            e.printStackTrace();
//        } catch (ClassNotFoundException e) {
//            e.printStackTrace();
//        }
    }
```

The password file has the following:

```java
    private static final String TABLE = "modus.db";
    private static final String URL = "jdbc:sqlite:D:\\Users\\Duncan Skilton\\IdeaProject\\modus\\src\\model\\" + TABLE;
```

This is the error: 

```
java.sql.SQLException: No suitable driver found for jdbc:sqlite:D:/Users/Duncan Skilton/IdeaProject/modus/src/model/modus.db
	at java.sql.DriverManager.getConnection(DriverManager.java:689)
	at java.sql.DriverManager.getConnection(DriverManager.java:270)
	at controller.databaseConnect.Connection(databaseConnect.java:16)
	at sample.Main.main(Main.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.sun.javafx.application.LauncherImpl.launchApplicationWithArgs(LauncherImpl.java:389)
	at com.sun.javafx.application.LauncherImpl.launchApplication(LauncherImpl.java:328)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at sun.launcher.LauncherHelper$FXHelper.main(LauncherHelper.java:767)
```

**Comment by Ayakk** [comment] 2022-06-22 11:57
Were you able to find a solution?

**Comment by gotson** [comment] 2022-07-28 09:48
The problem is not very clear to me. Also, is this still happening on the latest version?

**Comment by gotson** [comment] 2023-01-13 02:39
Closing this as no feedback was received.

**Closed by gotson** 2023-01-13 02:39 UTC
Labels: waiting for feedback
