### ISSUE TITLE
Native library doesn't load on ARM9 / causes app to abort

### ISSUE THREAD

**Issue by jasonbrice** [xerial/sqlite-jdbc#38] opened 2015-06-16 17:17 UTC
I'm having essentially this same issue as this resolved one --> [https://github.com/xerial/sqlite-jdbc/issues/32](https://github.com/xerial/sqlite-jdbc/issues/32 "https://github.com/xerial/sqlite-jdbc/issues/32")

Except my processor is a Freescale i.MX28 / ARM926EJ-S running Debian OS Version 3.14.27 and JDK OpenJDK Runtime Environment (IcedTea 2.5.5) (7u79-2.5.5-1~deb7u1) / JamVM (build 2.0.0).

I hacked together a xerial sqlite-jdbc.jar using the native arm .so library discussed here ---> [https://bitbucket.org/xerial/sqlite-jdbc/issue/79/compile-for-arm](https://bitbucket.org/xerial/sqlite-jdbc/issue/79/compile-for-arm "https://bitbucket.org/xerial/sqlite-jdbc/issue/79/compile-for-arm") and that caused a stack trace saying the library in /tmp could not be opened. 

When I use the most recent release (3.8.10.1) as-is, the app aborts with: 6414 Illegal instruction

**Comment by xerial** [comment] 2015-06-17 13:49
Could you try building a native library with `make native` and then running `mvn test`?

**Comment by xerial** [comment] 2015-08-03 15:18
Duplicate of #45

**Closed by xerial** 2015-08-03 15:18 UTC
