### ISSUE TITLE
java.sql.SQLException: Bad value for type BigDecimal

### ISSUE THREAD

**Issue by 29swastik** [xerial/sqlite-jdbc#779] opened 2022-09-02 07:06 UTC
**Describe the bug**
While extracting ResultSet JDBC driver is trying to extract String as BigDecimal

**To Reproduce**
 This is failing only for some SQL queries and working fine for other queries of same kind.  Looks like driver is not properly guessing data type of a value

**Logs**
`java.sql.SQLException: Bad value for type BigDecimal : An elegant piece with blue and white Zircon stones studded like a scintillating star-shaped evil eye to ward off the negative vibes. Available in Silver and Rose Gold Plating. 92.5 Sterling Silver AAA Cubic Zirconia Handcrafted and Electroplated with Rhodium for strength and luster. Consciously crafted with non-allergic materials, thus making it hypoallergenic. 92.5 Sterling Silver Authenticity Certificate included. All our jewellery is handcrafted and therefore variations may occur.\n\tat org.sqlite.jdbc3.JDBC3ResultSet.getBigDecimal(JDBC3ResultSet.java:190)\n\tat org.sqlite.jdbc3.JDBC3ResultSet.getBigDecimal(JDBC3ResultSet.java:199)\n\tat com.zaxxer.hikari.pool.HikariProxyResultSet.getBigDecimal(HikariProxyResultSet.java)
`

**Environment**

- SQLite JDBC driver - implementation("org.xerial:sqlite-jdbc:3.36.0.3")
- SQLite Dialect - implementation("com.github.gwenn:sqlite-dialect:0.1.0")

**Additional context**
I’m using SQLite + Hibernate in my JAVA app. While executing a SQL query using hibernate’s NativeQueryImpl class I'm getting the above mentioned exception. Below is my code which I’m using

```
  public List<Map<String, Object>> executeNativeQuery(String query) {
    NativeQueryImpl nativeQuery = (NativeQueryImpl) entityManager.createNativeQuery(query);
    nativeQuery.setResultTransformer(AliasToEntityMapResultTransformer.INSTANCE);
    return nativeQuery.getResultList();
  }
```

I’m calling executeNativeQuery function by passing a SQL query and getting the error at the line 
`return nativeQuery.getResultList();`
I thought the error is related to hibernate and raised the issue in their forum, but they thought it is not related to hibernate and redirected me here.

It would be really helpful if I get any help here

**Comment by gotson** [comment] 2022-09-02 07:11
Hi, can you provide a minimum reproducible example?

**Comment by 29swastik** [comment] 2022-09-02 07:18
SQL query I used

`WITH products AS ( SELECT i.position as image_position, v.product_id, v.variant_id, v.title, v.price,v.position, v.image_url, i.url FROM     shopify_variants v JOIN     shopify_images i where    v.product_id = i.product_id  AND      v.product_id IN ( SELECT * FROM   ( SELECT   p.product_id FROM     shopify_products p JOIN     shopify_collections c WHERE    p.product_id = c.product_id AND c.bot_ref = 76475 AND c.shop_domain = "silverlinejewellery.myshopify.com" AND p.status LIKE "ACTIVE" AND c.title="Talisman - The Evil Eye Capsule" GROUP BY p.product_id ORDER BY p.created_at DESC  LIMIT 30) AS limiter)) SELECT products.product_id,products.position, products.variant_id, products.title, products.price, products.url, products.image_url,pr.handle, pr.description, pr.title as productTitle  FROM   products JOIN   shopify_products pr WHERE products.product_id =pr.product_id ORDER BY pr.created_at DESC, products.image_position
`

And Result I exported by running SQL query through SQL UI

- [export.csv](https://github.com/xerial/sqlite-jdbc/files/9475786/export.csv)

**Comment by gotson** [comment] 2022-09-02 07:20
This is difficult to work with. Can you provide a minimum reproducible example as a separate github project, that reproduces the problem?

**Comment by 29swastik** [comment] 2022-09-02 07:35
I found that it is not easily replicable, It is working fine for same kind of queries.  If we see this error log, 
`java.sql.SQLException: Bad value for type BigDecimal : An elegant piece with blue and white Zircon stones`
and the file I've shared we can see `description` field is getting treated as BigDecimal. 

I'll be trying again to replicate

**Comment by gotson** [comment] 2022-09-02 07:49
But you're calling `org.sqlite.jdbc3.JDBC3ResultSet.getBigDecimal`, so it's not surprising you get the error.

**Comment by 29swastik** [comment] 2022-09-02 08:40
Let me explain in detail. I've not written any logic in my App to extract resultSet, since I'm using hibernate it is doing this for me. And hence first I raised this issue in Hibernate forum and they felt that it is not related to them and pointed out me here to check the issue

Discussion in Hibernate forum
https://discourse.hibernate.org/t/java-sql-sqlexception-bad-value-for-type-bigdecimal/6625

**Comment by gotson** [comment] 2022-09-02 08:42
You should have started by saying this, that would have helped

**Comment by gotson** [comment] 2022-09-02 10:48
Can you share the tables structure? Is that `pr.description` that causes the problem?

**Comment by 29swastik** [comment] 2022-09-03 11:20
Yeah looks like description is causing issue, but for the same query is working fine for some other values (i.e, if I change where condition values it is working). So looks like description `An elegant piece with blue and white Zircon stones` is getting treated as BigDecimal and causing the issue

`CREATE TABLE shopify_products (
  product_id bigint(20) NOT NULL,
  bot_ref int(11) NOT NULL,
  shop_domain varchar(200)  NOT NULL,
  tags varchar(1024)  DEFAULT NULL,
  description mediumtext  DEFAULT NULL,
  handle varchar(250) DEFAULT '',
  status varchar(50)  DEFAULT NULL,
  vendor varchar(50)  DEFAULT NULL,
  product_type varchar(50)  DEFAULT NULL,
  option_1 varchar(50)  DEFAULT NULL,
  option_1_value varchar(500)  DEFAULT NULL,
  option_2 varchar(50)  DEFAULT NULL,
  option_2_value varchar(500)  DEFAULT NULL,
  option_3 varchar(50)  DEFAULT NULL,
  option_3_value varchar(250)  DEFAULT NULL,
  title varchar(250) DEFAULT '',
  created_at datetime DEFAULT NULL,
  updated_at datetime DEFAULT NULL,
  PRIMARY KEY (product_id,bot_ref)
);`

`CREATE TABLE shopify_variants (
  variant_id bigint(20) NOT NULL,
  product_id bigint(20) NOT NULL,
  bot_ref int(11) NOT NULL,
  shop_domain varchar(200) NOT NULL,
  title varchar(250) NOT NULL,
  price float DEFAULT NULL,
  sku varchar(250) DEFAULT NULL,
  compare_at_price float DEFAULT NULL,
  image_url varchar(300) DEFAULT NULL,
  weight float DEFAULT NULL,
  weight_unit varchar(20) DEFAULT NULL,
  inventory_quantity int(10) DEFAULT NULL,
  created_at datetime DEFAULT NULL,
  updated_at datetime DEFAULT NULL,
  position int(11) DEFAULT NULL,
  PRIMARY KEY (variant_id,bot_ref)
);`


`CREATE TABLE shopify_collections (
  id INTEGER PRIMARY KEY,
  collection_id bigint(20) NOT NULL,
  bot_ref int(11) NOT NULL,
  shop_domain varchar(200) NOT NULL,
  description mediumtext DEFAULT NULL,
  handle varchar(250) NOT NULL,
  title varchar(250) NOT NULL,
  product_id bigint(20) NOT NULL,
  updated_at datetime DEFAULT NULL,
  image_url varchar(300) DEFAULT NULL
);`


`CREATE TABLE shopify_images (
  image_id bigint(20) NOT NULL,
  product_id bigint(20) NOT NULL,
  bot_ref int(11) NOT NULL,
  shop_domain varchar(200) NOT NULL,
  url varchar(200) DEFAULT NULL,
  position int(11) DEFAULT NULL,
  PRIMARY KEY (image_id,bot_ref)
);`

**Comment by gotson** [comment] 2022-09-03 12:01
I'm pretty sure the issue comes from the column type definition `mediumtext`. Could you try with the description as `varchar` instead?

**Comment by 29swastik** [comment] 2022-09-03 15:01
Thank you, will try it. May I know how `mediumtext` is causing the issue?

**Comment by gotson** [comment] 2022-09-04 05:21
> Thank you, will try it. May I know how `mediumtext` is causing the issue?

Sqlite is loosely typed, every value can be stored in a different container. The type of the column is just an indication.

The driver uses both the container type and the column definition to infer the jdbc type.

You can also try to explicitly cast the value to varchar in your query, see if that works.

**Comment by 29swastik** [comment] 2022-09-04 05:30
Thank you 🙌

**Comment by 29swastik** [comment] 2022-09-05 11:29
> I'm pretty sure the issue comes from the column type definition `mediumtext`. Could you try with the description as `varchar` instead?

I tried this approach but still giving same error. Tried both changing column definition and Cast-ing while querying
1. `  description VARCHAR(1024) DEFAULT NULL,`
2. `CAST(pr.description as VARCHAR(1024)) as description`

**Comment by gotson** [comment] 2022-09-05 11:40
@29swastik is that resolved?

**Comment by 29swastik** [comment] 2022-09-05 11:47
> @29swastik is that resolved?

Yes resolved by modifying Column Definition. I tried CAST but it didn't help.

Once again Thank you so much

**Comment by 29swastik** [comment] 2022-09-05 11:50
> > Thank you, will try it. May I know how `mediumtext` is causing the issue?
> 
> Sqlite is loosely typed, every value can be stored in a different container. The type of the column is just an indication.
> 
> The driver uses both the container type and the column definition to infer the jdbc type.
> 
> You can also try to explicitly cast the value to varchar in your query, see if that works.

Also It would be really helpful if you explain this in detail. i.e, why it failed for some string value and worked fine for other string values

**Comment by gotson** [comment] 2022-09-05 11:50
I'll keep this open, I think we could fix this in the driver, but I hadn't had any time to try to do a repro on my end.

**Comment by gotson** [comment] 2022-09-05 11:51
> > > Thank you, will try it. May I know how `mediumtext` is causing the issue?
> > 
> > 
> > Sqlite is loosely typed, every value can be stored in a different container. The type of the column is just an indication.
> > The driver uses both the container type and the column definition to infer the jdbc type.
> > You can also try to explicitly cast the value to varchar in your query, see if that works.
> 
> Also It would be really helpful if you explain this in detail. i.e, why it failed for some string value and worked fine for other string values

Yes the documentation would need some updates, it's tracked here : #777

**Comment by 29swastik** [comment] 2022-09-05 12:00
> I'll keep this open, I think we could fix this in the driver, but I hadn't had any time to try to do a repro on my end.

Can I contribute towards fixing this?

**Comment by gotson** [comment] 2022-09-05 12:15
> > I'll keep this open, I think we could fix this in the driver, but I hadn't had any time to try to do a repro on my end.
> 
> Can I contribute towards fixing this?

When I have time I will try to reproduce this in a unit test. If I can't I may ask you for more details or data.

**Comment by gotson** [comment] 2022-09-06 03:38
@29swastik i couldn't reproduce in a unit test.

Would you be able to test the following with the `sqlite3` command line:
```
select typeof(description) from shopify_products where product_id = <put your product id for the line that doesn't work here>;
```

**Comment by 29swastik** [comment] 2022-09-06 04:30
surprisingly this query is giving `typeof(description)` as `text`, though while creating table I specified column as VARCHAR(1024)

<img width="683" alt="image" src="https://user-images.githubusercontent.com/65583094/188547203-8068a5ee-fe3e-4296-a191-f6a64f7333d0.png">

**Comment by gotson** [comment] 2022-09-06 05:25
Can you try that with the initial table where it was `mediumtext`?

**Comment by 29swastik** [comment] 2022-09-06 05:31
> Can you try that with the initial table where it was `mediumtext`?

with old table definition also it is showing as `text`

**Comment by gotson** [comment] 2022-09-06 07:12
`text` is expected, it's the storage class for the value, so nothing wrong there.

**Comment by gotson** [comment] 2022-09-11 04:27
Well, I can't reproduce the issue on my end. If you're OK with it I'll close this?

**Comment by 29swastik** [comment] 2022-09-11 15:00
> Well, I can't reproduce the issue on my end. If you're OK with it I'll close this?

Yeah sure, anyway VARCHAR instead of text worked

**Closed** 2022-09-11 15:12 UTC
Labels: troubleshooting
