### ISSUE TITLE
java.lang.UnsatisfiedLinkError: org.sqlite.core.NativeDB._open_utf8([BI)V

### ISSUE THREAD

**Issue by Eternity-Yarr** [xerial/sqlite-jdbc#197] opened 2017-01-14 18:11 UTC
I'm still getting this error with latest (3.16.1) version on ubuntu server with correct java tmpdir property.

```
java.lang.UnsatisfiedLinkError: org.sqlite.core.NativeDB._open_utf8([BI)V
	at org.sqlite.core.NativeDB._open_utf8(Native Method) ~[sqlite-jdbc-3.16.1.jar!/:na]
	at org.sqlite.core.NativeDB._open(NativeDB.java:71) ~[sqlite-jdbc-3.16.1.jar!/:na]
	at org.sqlite.core.DB.open(DB.java:174) ~[sqlite-jdbc-3.16.1.jar!/:na]
	at org.sqlite.core.CoreConnection.open(CoreConnection.java:220) ~[sqlite-jdbc-3.16.1.jar!/:na]
	at org.sqlite.core.CoreConnection.<init>(CoreConnection.java:76) ~[sqlite-jdbc-3.16.1.jar!/:na]
	at org.sqlite.jdbc3.JDBC3Connection.<init>(JDBC3Connection.java:26) ~[sqlite-jdbc-3.16.1.jar!/:na]
	at org.sqlite.jdbc4.JDBC4Connection.<init>(JDBC4Connection.java:24) ~[sqlite-jdbc-3.16.1.jar!/:na]
	at org.sqlite.SQLiteConnection.<init>(SQLiteConnection.java:45) ~[sqlite-jdbc-3.16.1.jar!/:na]
	at org.sqlite.JDBC.createConnection(JDBC.java:114) ~[sqlite-jdbc-3.16.1.jar!/:na]
	at org.sqlite.JDBC.connect(JDBC.java:88) ~[sqlite-jdbc-3.16.1.jar!/:na]
	at org.apache.tomcat.jdbc.pool.PooledConnection.connectUsingDriver(PooledConnection.java:310) ~[tomcat-jdbc-8.5.6.jar!/:na]
	at org.apache.tomcat.jdbc.pool.PooledConnection.connect(PooledConnection.java:203) ~[tomcat-jdbc-8.5.6.jar!/:na]
	at org.apache.tomcat.jdbc.pool.ConnectionPool.createConnection(ConnectionPool.java:718) ~[tomcat-jdbc-8.5.6.jar!/:na]
	at org.apache.tomcat.jdbc.pool.ConnectionPool.borrowConnection(ConnectionPool.java:650) ~[tomcat-jdbc-8.5.6.jar!/:na]
	at org.apache.tomcat.jdbc.pool.ConnectionPool.init(ConnectionPool.java:468) ~[tomcat-jdbc-8.5.6.jar!/:na]
	at org.apache.tomcat.jdbc.pool.ConnectionPool.<init>(ConnectionPool.java:143) ~[tomcat-jdbc-8.5.6.jar!/:na]
	at org.apache.tomcat.jdbc.pool.DataSourceProxy.pCreatePool(DataSourceProxy.java:118) ~[tomcat-jdbc-8.5.6.jar!/:na]
	at org.apache.tomcat.jdbc.pool.DataSourceProxy.createPool(DataSourceProxy.java:107) ~[tomcat-jdbc-8.5.6.jar!/:na]
	at org.apache.tomcat.jdbc.pool.DataSourceProxy.getConnection(DataSourceProxy.java:131) ~[tomcat-jdbc-8.5.6.jar!/:na]
	at org.springframework.jdbc.datasource.DataSourceUtils.doGetConnection(DataSourceUtils.java:111) ~[spring-jdbc-4.3.5.RELEASE.jar!/:4.3.5.RELEASE]
````

**Comment by Eternity-Yarr** [comment] 2017-01-14 18:14
` java -version
openjdk version "1.8.0_111"
OpenJDK Runtime Environment (build 1.8.0_111-8u111-b14-2ubuntu0.16.04.2-b14)
OpenJDK 64-Bit Server VM (build 25.111-b14, mixed mode)`

**Comment by Eternity-Yarr** [comment] 2017-01-14 18:14
```
 java -version
openjdk version "1.8.0_111"
OpenJDK Runtime Environment (build 1.8.0_111-8u111-b14-2ubuntu0.16.04.2-b14)
OpenJDK 64-Bit Server VM (build 25.111-b14, mixed mode
```

**Comment by xerial** [comment] 2017-01-30 17:42
Please report your OS, cpu type, etc. We need to know your JVM property os.name and os.arch to investigate this.

**Comment by Eternity-Yarr** [comment] 2017-02-03 21:56
```
$ cat /etc/issue
Ubuntu 16.04.1 LTS \n \l
$ cat /proc/cpuinfo
cat /proc/cpuinfo 
processor	: 0
vendor_id	: GenuineIntel
cpu family	: 6
model		: 42
model name	: Intel(R) Xeon(R) CPU E5-26xx (Sandy Bridge)
stepping	: 1
microcode	: 0x1
cpu MHz		: 2099.998
cache size	: 4096 KB
physical id	: 0
siblings	: 1
core id		: 0
cpu cores	: 1
apicid		: 0
initial apicid	: 0
fpu		: yes
fpu_exception	: yes
cpuid level	: 13
wp		: yes
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 syscall nx rdtscp lm constant_tsc rep_good nopl eagerfpu pni pclmulqdq ssse3 cx16 sse4_1 sse4_2 x2apic popcnt tsc_deadline_timer aes xsave avx hypervisor lahf_lm xsaveopt arat
bugs		:
bogomips	: 4199.99
clflush size	: 64
cache_alignment	: 64
address sizes	: 40 bits physical, 48 bits virtual
power management:

OS Architecture : amd64
OS Name : Linux
OS Version : 4.4.0-38-generic
Data Model : 64
```

**Comment by Eternity-Yarr** [comment] 2017-02-03 21:57
I downgraded to 3.8.11.2 as workaround

**Comment by bertmaher** [comment] 2017-06-08 04:22
It seems likely that there's a race condition in loading the native library.  I created a small repro here: https://gist.github.com/bertmaher/6bfadd9543a43b2d5c19cce93c7a2326.
This reliably fails for me unless I synchronize the connection creation (system info: MacOS 10.12.3, 2016 15" MacBook Pro, JVM 1.8.0_131).  I had to twiddle the argument to Thread.sleep() a bit before it started failing, so it's a bit subtle.

I only looked briefly at the code, but it seems like the cause could be a race between SQLiteJDBCLoader.cleanup on one thread and SQLiteJDBCLoader.extractAndLoadLibraryFile on another.

**Comment by MartyIX** [comment] 2017-07-20 07:15
I have experienced the same error (version 3.19.3).

```
Caused by: java.lang.UnsatisfiedLinkError: org.sqlite.core.NativeDB._open_utf8([BI)V
        at org.sqlite.core.NativeDB._open_utf8(Native Method)
        at org.sqlite.core.NativeDB._open(NativeDB.java:71)
        at org.sqlite.core.DB.open(DB.java:174)
        at org.sqlite.core.CoreConnection.open(CoreConnection.java:220)
        at org.sqlite.core.CoreConnection.<init>(CoreConnection.java:76)
        at org.sqlite.jdbc3.JDBC3Connection.<init>(JDBC3Connection.java:26)
        at org.sqlite.jdbc4.JDBC4Connection.<init>(JDBC4Connection.java:24)
        at org.sqlite.SQLiteConnection.<init>(SQLiteConnection.java:45)
        at org.sqlite.JDBC.createConnection(JDBC.java:114)
        at org.sqlite.JDBC.connect(JDBC.java:88)
        at java.sql.DriverManager.getConnection(DriverManager.java:664)
        at java.sql.DriverManager.getConnection(DriverManager.java:208)
        at com.project.storages.sqlite.ConnectionManager.getConnection(ConnectionManager.java:47)
        at com.project.storages.sqlite.SqliteStorage.storeTopOfTheBook(SqliteStorage.java:49)
        at com.project.MainThread.onEvent(MainThread.java:119)
        at com.project.MainThread.onEvent(MainThread.java:36)
        at com.lmax.disruptor.BatchEventProcessor.run(BatchEventProcessor.java:129)
        ... 1 common frames omitted

```


```
$ java -version
java version "1.8.0_131"
Java(TM) SE Runtime Environment (build 1.8.0_131-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.131-b11, mixed mode)

$ uname -a
Linux domain.net 3.16.0-4-amd64 #1 SMP Debian 3.16.36-1+deb8u2 (2016-10-19) x86_64 GNU/Linux

$ cat /etc/issue
Debian GNU/Linux 8 \n \l

$ cat /proc/cpuinfo
processor	: 0
vendor_id	: GenuineIntel
cpu family	: 6
model		: 44
model name	: Intel(R) Xeon(R) CPU           E5620  @ 2.40GHz
stepping	: 2
microcode	: 0x14
cpu MHz		: 2400.176
cache size	: 12288 KB
physical id	: 0
siblings	: 4
core id		: 9
cpu cores	: 1
apicid		: 18
initial apicid	: 18
fpu		: yes
fpu_exception	: yes
cpuid level	: 11
wp		: yes
flags		: fpu de tsc msr pae cx8 apic sep cmov pat clflush mmx fxsr sse sse2 ss ht syscall nx lm constant_tsc rep_good nopl pni ssse3 cx16 sse4_1 sse4_2 popcnt hypervisor lahf_lm ida arat epb dtherm
bogomips	: 4800.35
clflush size	: 64
cache_alignment	: 64
address sizes	: 40 bits physical, 48 bits virtual
power management:

processor	: 1
vendor_id	: GenuineIntel
cpu family	: 6
model		: 44
model name	: Intel(R) Xeon(R) CPU           E5620  @ 2.40GHz
stepping	: 2
microcode	: 0x14
cpu MHz		: 2400.176
cache size	: 12288 KB
physical id	: 0
siblings	: 4
core id		: 9
cpu cores	: 1
apicid		: 18
initial apicid	: 18
fpu		: yes
fpu_exception	: yes
cpuid level	: 11
wp		: yes
flags		: fpu de tsc msr pae cx8 apic sep cmov pat clflush mmx fxsr sse sse2 ss ht syscall nx lm constant_tsc rep_good nopl pni ssse3 cx16 sse4_1 sse4_2 popcnt hypervisor lahf_lm ida arat epb dtherm
bogomips	: 4800.35
clflush size	: 64
cache_alignment	: 64
address sizes	: 40 bits physical, 48 bits virtual
power management:

processor	: 2
vendor_id	: GenuineIntel
cpu family	: 6
model		: 44
model name	: Intel(R) Xeon(R) CPU           E5620  @ 2.40GHz
stepping	: 2
microcode	: 0x14
cpu MHz		: 2400.176
cache size	: 12288 KB
physical id	: 0
siblings	: 4
core id		: 9
cpu cores	: 1
apicid		: 18
initial apicid	: 18
fpu		: yes
fpu_exception	: yes
cpuid level	: 11
wp		: yes
flags		: fpu de tsc msr pae cx8 apic sep cmov pat clflush mmx fxsr sse sse2 ss ht syscall nx lm constant_tsc rep_good nopl pni ssse3 cx16 sse4_1 sse4_2 popcnt hypervisor lahf_lm ida arat epb dtherm
bogomips	: 4800.35
clflush size	: 64
cache_alignment	: 64
address sizes	: 40 bits physical, 48 bits virtual
power management:

processor	: 3
vendor_id	: GenuineIntel
cpu family	: 6
model		: 44
model name	: Intel(R) Xeon(R) CPU           E5620  @ 2.40GHz
stepping	: 2
microcode	: 0x14
cpu MHz		: 2400.176
cache size	: 12288 KB
physical id	: 0
siblings	: 4
core id		: 9
cpu cores	: 1
apicid		: 18
initial apicid	: 18
fpu		: yes
fpu_exception	: yes
cpuid level	: 11
wp		: yes
flags		: fpu de tsc msr pae cx8 apic sep cmov pat clflush mmx fxsr sse sse2 ss ht syscall nx lm constant_tsc rep_good nopl pni ssse3 cx16 sse4_1 sse4_2 popcnt hypervisor lahf_lm ida arat epb dtherm
bogomips	: 4800.35
clflush size	: 64
cache_alignment	: 64
address sizes	: 40 bits physical, 48 bits virtual
power management:

```

**Comment by MartyIX** [comment] 2017-08-06 18:15
Should this issue be closed now?

**Comment by trohwer** [comment] 2017-09-10 16:26
I can still reproduce this; in fact, the lock file is still created _after_ the lib file. The file creation was simply moved before writing the lib file. But this still leaves a small window for the cleanup function finding the lib file, but not the lock file. I would also recommend (in addition) to synchronize the initialization in addition to not create multiple libs in vain (see #269).

**Comment by bitsofinfo** [comment] 2017-12-15 21:18
same issue on 3.20.1, docker, alpine image

**Comment by xerial** [comment] 2017-12-15 23:28
@bitsofinfo For alpine Linux, we need to use an alpine image with glibc:
https://wiki.alpinelinux.org/wiki/Running_glibc_programs
https://hub.docker.com/r/frolvlad/alpine-glibc/

**Comment by xerial** [comment] 2017-12-15 23:29
@trohwer Now that #271 is merged, let me close this issue. If you still see the issue, please open another ticket.

**Closed by xerial** 2017-12-15 23:29 UTC

**Comment by trohwer** [comment] 2018-02-01 05:26
Sorry, I missed this message. Yes, it can be closed.
