### ISSUE TITLE
support mips64 arch

### ISSUE THREAD

**Issue by Paradox98** [xerial/sqlite-jdbc#784] opened 2022-09-13 02:41 UTC
**Is your feature request related to a problem? Please describe.**
When sqlite-jar is running, it will take out the corresponding dynamic library from the jar according to the computer architecture. At present, the dynamic library of mips64 architecture is not carried in sqlite-jar. I hope the community can add it.

**Describe the solution you'd like**
Compile the dynamic library of the mips64 architecture and hit the jar package org\sqlite\native\Linux\mips64  path 

**Describe alternatives you've considered**
Compile the dynamic library of the mips64 architecture and hit the jar package org\sqlite\native\Linux\mips64  path 

**Additional context**
nothing

**Comment by gotson** [comment] 2022-09-13 02:56
Duplicate of #624

**Closed by gotson** 2022-09-13 02:56 UTC
Labels: triage
