### ISSUE TITLE
how to set sqlite3_limit() or SQLITE_LIMIT_ATTACHED

### ISSUE THREAD

**Issue by zzhgb** [xerial/sqlite-jdbc#550] opened 2020-10-20 07:05 UTC
help:
, to attach db number limit above 10?
thanks

**Comment by jehugaleahsa** [comment] 2020-10-23 22:20
This is probably a duplicate of this: https://github.com/xerial/sqlite-jdbc/issues/523

**Closed** 2022-07-26 11:47 UTC
Labels: duplicate
