### ISSUE TITLE
Get ID of the last inserted row throws error

### ISSUE THREAD

**Issue by sheriffmarley** [xerial/sqlite-jdbc#447] opened 2019-08-16 12:53 UTC
How do I get the ID of the latest inserted row? 

I tried
```java
PreparedStatement ps = connection.prepareStatement("INSERT INTO paths (path, storage) VALUES (?, ?)");
ps.setString(1, path);
ps.setString(2, "local");
ps.execute();

ResultSet rs = ps.getResultSet();
rs.getRowId(1);
```

but i receive a `NullPointerException`.

If I tried it this way:
```java
Statement stmt = connection.createStatement();
			
stmt.execute("INSERT INTO directories (path, storage) VALUES ("+path+", 'local');", Statement.RETURN_GENERATED_KEYS);
			
ResultSet rs = stmt.getResultSet();
				
System.out.println("key: " + rs.getRowId(1));
```

I receive `java.sql.SQLException: not implemented by SQLite JDBC driver`.

I also tried 
```java
ResultSet rs = stmt.getGeneratedKeys();
```
but i receive `java.sql.SQLException: not implemented by SQLite JDBC driver` again.

I'm using the latest version of this package, 3.28.0 . 

Am I missing something, or is it a bug?

**Comment by witmoca** [comment] 2019-08-16 13:06
It's not a bug. The exceptions aren't lying, sqlite-jdbc does not implement this method. 
Why you'd get a `NullPointerException` in the first case is beyond me without looking into the code (could you check if the path variable in the first case isn't a null, just to be sure?). You should've received the same not implemented exception as the others. 

The fact is that sqlite doesn't support this kind of feedback by itself to my knowledge, so neither does sqlite-jdbc. I suggest you either insert the rowid yourself, so you already have it, or do a select statement to retrieve it.

**Comment by gotson** [comment] 2022-07-28 08:11
Seems the question was answered, i'm closing this. Comment if necessary.

**Closed by gotson** 2022-07-28 08:11 UTC
