### ISSUE TITLE
jdbc potential memory leak

### ISSUE THREAD

**Issue by mhanna** [xerial/sqlite-jdbc#938] opened 2023-07-13 12:47 UTC
**Describe the bug**
Using a yourkit to capture memory used by java application that uses thousands of prepared statements and non prepared statements to sqlite, i can see that the NativeDB's safeStmt set is much more than the statements is should track.. see screenshot

**To Reproduce**
Maybe run many prepare/non-prepare statements 

**Expected behavior**

**Logs**
![image](https://github.com/xerial/sqlite-jdbc/assets/4300364/fa95c1a1-5168-41c3-8c58-2755f62f4750)

**Environment (please complete the following information):**
 - OS: Centos
 - CPU architecture: x86_64]
 - sqlite-jdbc version [e.g. 3.39.2.0]

Do you see any issue here?

**Comment by rhyswilliamsza** [comment] 2023-07-18 07:59
I am experiencing a similar issue on Java 11.0.19, but not Java 11.0.16. Will confirm if it's the same issue soon.

**Comment by rhyswilliamsza** [comment] 2023-07-18 08:01
I am potentially experiencing a similar issue on Java 11.0.19, but not Java 11.0.16. Which version of Java are you running?

**Comment by mhanna** [comment] 2023-07-18 15:11
openjdk version "17" 2021-09-14 OpenJDK Runtime Environment (build 17+35-2724) OpenJDK 64-Bit Server VM (build 17+35-2724, mixed mode, sharing)
________________________________

**Comment by mhanna** [comment] 2023-08-27 08:48
@gotson can anyone shed light on this?

**Comment by gotson** [comment] 2023-08-27 09:28
> @gotson can anyone shed light on this?

Someone would need to provide evidence of where the leak happens.

**Comment by noahboegli** [comment] 2023-10-15 09:31
@mhanna I had exactly the same problem as you. A program running for 6+ hours doing requests and requests to an SQLite db. 

The debian box has 6 GB of RAM and a variant of the program that does not make use of SQLite runs with less than 512MB.

After inspecting with VisualVM I found out that the instances of `SafeStmtPtr` were through the roof.

Simply closing the Statement calling `close()` solved my issue. I believe you should also be able to set them to automatically close on complete, although I haven't tested this.

I assume not closing the statement leaves some memory out of the JVM to remain allocated and when the `SafeStmtPtr` is collected the memory is leaked. Although this is a wild guess and I don't really know about JDBC's or SQLite's internals.

**Comment by noahboegli** [comment] 2023-10-16 05:44
On my end it was less practical to use a try-with-resources due to a catch and error forwarding nightmare, there was a `close()` call in the catch but not if the statement was successful. 

But the JavaDoc for Statement/Prepared statement is confusing

> Releases this Statement object's database and JDBC resources immediately instead of waiting for this to happen when it is automatically closed. It is generally good practice to release resources as soon as you are finished with them to avoid tying up database resources.

So technically, while not a good practice, it should not leak memory if not done. 

I have no proof of causality, but adding the close no matter what the outcome of the execution eliminated the memory leak.

Example based on the code that caused the leak. It's not ideal but it's the code I have to work with. The try-catch is removed for clarity.
```java
// columns is a String[], value is Map<String, String>, query is String 
PreparedStatement pStmt = connection.prepareStatement(query);
for (int i = 1; i <= columns.length; ++i) {
    pStmt.setString(i, this.values.get(columns[i - 1]));
}
pStmt = insert.getStatement(this.connection);
pStmt.execute();

// This line fixes it
pStmt.close();
```

To give a bit of context, this code is called in average 270 per file we process and we process around 4000 per run. A run lasts 8 hours. So over the course of those 8 hours, a little bit over a million times. The leak will likely not be noticeable for normal loads and only becomes a problem in large scale situations.

**Comment by jeseibel** [comment] 2023-10-23 12:50
I can confirm that try-resource blocks (specifically around `statement`s and `ResultSet`s) are necessary to prevent native code memory leaks. Java never went over the max heap allocation in my testing, however in Task Manager I saw the JVM's total memory steadily rise as queries were run.

Here is a commit I did that fixed the memory leak for my project:
https://gitlab.com/jeseibel/distant-horizons-core/-/commit/b38b33e87e0bc25837220046767d732dba4e0053

**Comment by noahboegli** [comment] 2023-10-24 08:55
Based on the observation that it's not `Statement` objects remaining in memory but `SafeStmtPtr` objects, I assume the Statement object is collected and leaves the `SafeStmtPtr` that should normally be properly "destroyed" when closing the `Statement`

If you look at the `Statement` class of the jTDS driver (which is used in the same codebase I have sqlite in, and does not leak): 

```java
protected void finalize() throws Throwable {
    super.finalize();
    try {
        close();
    } catch (SQLException e) {
        // Ignore errors
    }
}
```

I was not able to find such usage of the `finalize()` in the sqlite driver. I've only searched in the github web UI so if I missed it my bad.

However since finalization is deprecated in [release 18 through JEP 421](https://openjdk.org/jeps/421)  I don't know what would be the proper way of cleaning underlying resources upon garbage collection of the Statement objects. [The documentation](https://docs.oracle.com/en/java/javase/21/docs/api/java.base/java/lang/Object.html#finalize()) mentions the [Cleaner class](https://docs.oracle.com/en/java/javase/21/docs/api/java.base/java/lang/ref/Cleaner.html) but I've never actually used it.

The JEP 421 also mentions the use of `try-with-resources` and all others mechanisms of properly handling closable resources and it should be used, but it does not address the memory leak.

**Comment by hbobenicio** [comment] 2024-02-18 17:45
Connection and Statement are AutoCloseable. So we should **really** care about closing them in order to avoid leaks (ideally with try-with-resources).

Most of this confusion about not closing Statements really comes mostly from examples in the docs and code that completely forget to close them (like in readme.md and in demo/Sample.java).

I strongly believe we should update every example in the project to also correctly close Statements (not only Connections).

**Comment by gotson** [comment] 2024-02-19 01:24
> Most of this confusion about not closing Statements really comes mostly from examples in the docs and code that completely forget to close them (like in readme.md and in demo/Sample.java).
> 
> I strongly believe we should update every example in the project to also correctly close Statements (not only Connections) so then they would not induce or mislead into leaking issues.

as always, PRs are welcome :)

**Comment by hbobenicio** [comment] 2024-02-20 14:39
Submitted PR #1073 .
What do you think?

**Comment by gotson** [comment] 2024-02-21 09:03
> Submitted PR #1073 . What do you think?

will have a look when time allows, thanks !

**Closed** 2024-02-22 05:44 UTC
Labels: troubleshooting
