### ISSUE TITLE
DriverManager.getConnection() hangs on some PCs

### ISSUE THREAD

**Issue by BullyWiiPlaza** [xerial/sqlite-jdbc#459] opened 2019-11-06 18:47 UTC
A while ago I created [a question on `StackOverflow`](https://stackoverflow.com/questions/58471559) about this issue I've been told about by certain users but the question has not attracted enough attention.

In summary:
Trying to open a connection to a (local) `SQLite` database `.db` file may get stuck for an undetermined amount of time. I've heard users say it was 5 minutes or an hour which is ridiculous since for me it always succeeds within seconds. This is the "offending" piece of code:

```
String className = JDBC.class.getName();
Class.forName(className); // Maybe unnecessary, added as a mitigation attempt which seemingly failed
String connectionString = JDBC.PREFIX + databaseFilePath;
DriverManager.getConnection(connectionString); // <-- May get stuck/stall for very long
```

Any ideas why this might happen? Sure, this bug is hard or impossible to replicate but there must be a reason why it sometimes happens to 2 or so users.

Thanks a lot for any tips on meaningfully restructuring my database access code or debugging this problem efficiently. I'm unsure if any alternatives exist which I could try since this bug is quite a deal-breaker when the essential database access is not working reliably.

**Comment by witmoca** [comment] 2019-11-06 20:55
Indeed a though problem to reproduce. We'll have to go by what you can tell us then. Does this consistently happen for that user? Is there anything special about that users name (non standard characters, more characters in the name,...), his access rights? Is the `databaseFilePath` different for the different users?

But most importantly:
While debugging, can you step into the `Drivermanager.getConnection` function to more accurately pinpoint where it goes wrong?

**Comment by BullyWiiPlaza** [comment] 2019-11-12 15:57
@witmoca Alright, I had the time to do debugging on the user's machine.

I saw the following delay:
```
[INFO ] 22:32:35.094 [pool-2-thread-1]: Connecting database...
[INFO ] 22:53:42.239 [pool-2-thread-1]: Querying database...
```

That is 21 minutes.

`Does this consistently happen for that user?`
Yes, kind of. After a reboot or a long PC sleep. Once the connection succeeds, it will continue to connect fast.

`Is there anything special about that user's name (non standard characters, more characters in the name, ...)`
No, the username is totally normal (`Acer`).

`His access rights?`
Nothing weird, it's a local account with administrator rights.

An oddity I noticed is his operating system. He's running a "custom" OS as follows:
```
Windows 10 Enterprise N 2015 LTSB
(C) 2015 Microsoft Corporation. All rights reserved.
```
Windows Update does not work and seems to be disabled since the service has been deleted he says.

`While debugging, can you step into the Drivermanager.getConnection function to more accurately pinpoint where it goes wrong?`
The exact line where it gets stuck is `java.sql.Driver#connect`. The call is `Connection con = aDriver.driver.connect(url, info);`.

`Is the databaseFilePath different for the different users?`
No. Well, it's kind of randomized but it's not the reason for the issue since some users get it consistently and others never.

**Comment by roychen11232357** [comment] 2020-01-08 03:23
I also faced the same issue, my development environment is

# window 10
# openjdk version "1.8.0_222"
# sqlite-jdbc 3.28.0


Is there any solutions?

thanks

**Comment by roychen11232357** [comment] 2020-03-17 03:04
sorry for bothering, I add some details about this issue,

Program is hanging at DriverManager.java

` Connection con = aDriver.driver.connect(url, info);`

I continue to trace down, I found the Character.java is keeping recalled at toLowerCase

Is there any solutions?

thanks


toLowerCase,

**Comment by martinmeeser** [comment] 2020-11-09 07:44
I am having this problem with Ubuntu 20, openJdk 14.1, and 
implementation group: 'org.xerial', name: 'sqlite-jdbc', version: '3.32.3.2'

I am using gradle 6.7 and I am putting everything to the module-path, using jdbc as automatic module.

I have done this module-path thing before with 3.31.1 and a Apache Netbeans ant-build and had NO SUCH problems.

--
I have debugged into the problem and it is somewhere at
SQLiteJDBCLoader::325
sqliteNativeLibraryPath = String.format("/%s/native/%s", packagePath, OSInfo.getNativeLibFolderPathForCurrentOS());

seems like OSInfo::getArchName is causing it.

Oddly I was able to resolve the problem as follows:


```
        try {
            _connection = DriverManager.getConnection(connectionString);
        } catch (Exception ex) { // works with Exception, hangs with SQLException
            Logger.getLogger(SqliteStorageManager.class.getName()).log(Level.SEVERE, null, ex);
        }
```

**Comment by martinmeeser** [comment] 2020-11-09 20:44
Update:
Problems seems to be:
OSInfo::isAlpine

118 Process p = Runtime.getRuntime().exec("cat /etc/os-release | grep ^ID");
119           p.waitFor();   // blocks

**Comment by martinmeeser** [comment] 2022-03-07 10:49
The fix got merged into master quite some time ago

**Comment by gotson** [comment] 2022-07-28 08:10
Is this still an issue on the latest version ?

**Comment by BullyWiiPlaza** [comment] 2022-07-28 08:26
> Is this still an issue on the latest version ?

I stopped using SQLite for my project (not because of this bug but for other reasons) so I'm no longer involved in testing whether this has been fixed or not. After all, this bug only occurred on some people's machines.

**Comment by martinmeeser** [comment] 2022-07-28 08:56
I haven't seen this issue any more. I am still using SQLite recently.

**Comment by gotson** [comment] 2022-07-28 09:42
Thanks, i will close this.

**Closed by gotson** 2022-07-28 09:42 UTC
Labels: waiting for feedback
