### ISSUE TITLE
Infrequent SIGSEGV crash - pthread_mutex_lock+0x4

### ISSUE THREAD

**Issue by tildedave** [xerial/sqlite-jdbc#509] opened 2020-06-29 19:10 UTC
Hi, we've been seeing infrequent crashes on xerial/sqlite-jdbc 3.31.1.  This happens really infrequently (about once a week) so pinning it down has been difficult.  I also haven't been able to get a working core dump here yet.  Creating this issue to try to see if anyone else has seen anything like this.  

# Extra info

* Previous version was xerial/sqlite-jdbc 3.28.1-SNAPSHOT - no issues.  I have been making a number of changes to how our application interacts with SQLite over the last few weeks so I don't know that this issue is related (or not) to the upgrade.
* Have upgraded to 3.32.3 (also added `-g` to the SQLite compilation options in Makefile.common) to see if that would change anything and no dice.
* We are running a few local custom modifications to the library but nothing really related to this.

If I get more information or can reproduce this consistently I'll update the issue and submit a PR.

# Toplevel crash info

```
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x00007f6e7cca9d44, pid=438, tid=0x00007f6d2d66c700
#
# JRE version: Java(TM) SE Runtime Environment (8.0_171-b11) (build 1.8.0_171-b11)
# Java VM: Java HotSpot(TM) 64-Bit Server VM (25.171-b11 mixed mode linux-amd64 compressed oops)
# Problematic frame:
# C  [libpthread.so.0+0x9d44]  pthread_mutex_lock+0x4
#
# Failed to write core dump. Core dumps have been disabled. To enable core dumping, try "ulimit -c unlimited" before starting Java again
#
# If you would like to submit a bug report, please visit:
#   http://bugreport.java.com/bugreport/crash.jsp
# The crash happened outside the Java Virtual Machine in native code.
# See problematic frame for where to report the bug.
#
```

# Investigation

The crash report itself doesn't look too useful and it happens while a bunch of other work is being done in the system so including it verbatim seems like it would just be noise.  

What I did pin down from it is this:
```
Java frames: (J=compiled Java code, j=interpreted, Vv=VM code)
J 4947  org.sqlite.core.NativeDB.step(J)I (0 bytes) @ 0x00007f6e65d5ed18 [0x00007f6e65d5ece0+0x38]
```

From looking at the code it looks like this is happening in ResultSet.next(), which calls `step` which calls into `sqlite3_step`. https://github.com/xerial/sqlite-jdbc/blob/2f473d539068ac0ff08edfe4bcbc76ad4f27c445/src/main/java/org/sqlite/jdbc3/JDBC3ResultSet.java#L73-L86

`sqlite3_step` is what steps through the ResulSet and interacts with pthreads through its own sqlite3_mutex_enter interface: https://github.com/sqlite/sqlite/blob/2bfd35b8d2871012f3061c89aef9cdb6ad7dbd94/src/vdbeapi.c#L749-L760

What's calling into this from our code is a piece of code that's turning a `ResultSet` into an `InputStream`.  This code is exercised without issue a good amount so I'm guessing this is some crazy race condition where the database has been somehow invalidated prior to `next()` being called.

I'll update this issue when I learn more - I understand it's not really in an actionable state without a reproducible test case or more complete crash log.  Thanks.

**Comment by tildedave** [comment] 2020-07-16 16:07
Thanks, nice to know it's not just us seeing this.  I found a client-side workaround that has caused the crashes to stop.

Background: In our system we mediate SQLite connections through an instance of Apache commons-pool2.  We recently started to run an eviction thread that closes connections that are open "too long", after which we started to see this.  ResultSet is opened from a PreparedStatement in one thread, the connection is killed in another.

I ended up passing in the connection to the place in the code that was calling `ResultSet#next` and not calling `next` in the case that the connection was no longer open - after making that change we haven't seen any more crashes.  It's only been a few weeks though.

I'm planning to look more into this in a few weeks or so, hopefully we can figure out what's causing this.

**Comment by ranjitkollu1** [comment] 2020-07-16 16:11
Thank you Dave for letting us know. We have a complicated environment where we have JOOQ as the abstraction layer via which we make the DB calls. Our environment is highly parallelized/asynchronous running in RxJava and Vertx.  We haven't figured out a work around yet as all our code uses JOOQ abstraction.

**Comment by tildedave** [comment] 2020-07-19 19:58
Looking over the code, one possibility is that the driver should be using `sqlite_close_v2` instead of `sqlite_close` in the NativeDB in order to close its connections.  https://www.sqlite.org/c3ref/close.html indicates the the `v2` is more appropriate for Java where destructor order is arbitrary.  My scenario is directly related to closing a connection while a query is still running.  I should be able to create a test case to confirm this.

**Comment by tildedave** [comment] 2020-08-10 17:25
I disabled the SQLite evictor (closes connections in a separate thread from the queries) two weeks ago and we haven't had any further crashes.

I'm still planning to revisit making an upstream fix here but for anyone else hitting this it might be a good idea to disable any cross-thread connection closing that might exist in your system.

**Comment by ranjitkollu1** [comment] 2020-08-10 17:30
@tildedave Our code base is extremely complicated we use Jooq as an abstraction layer for different databases. I think it would better for us to get the fix as part of a SQLite update and add the new version with the fix to our pom file. Is there a timeline when the fix will be available and part of which version of the SQLite release ?

**Comment by tildedave** [comment] 2020-08-11 16:26
Hey @ranjitkollu1 I'm not a maintainer of the library, just an active user.  My recommendation if this is a critical issue for you would be for you to create a fork of this repo and implement the patch I outlined here https://github.com/xerial/sqlite-jdbc/issues/509#issuecomment-660699527.  If it works for you in your system it's probably the right fix the for upstream library.  No guarantees it will work.  (This is the process I've used for similar issues with the library in the past - deploy fork locally, promote to upstream.)

**Comment by ranjitaskdesis** [comment] 2020-09-22 13:55
Any maintainer of this code base looking at this issue ?. Any updates on the fix ?

**Comment by tildedave** [comment] 2020-12-04 15:59
I deployed the change to use `sqlite_close_v2` to our production applications and we still had crashes, so I don't believe the issue is as simple as just changing the function call here.

**Comment by pyckle** [comment] 2021-11-08 08:05
Hi @tildedave 

I suspect that I had the same issue as you, and I wrote a patch, along side a unit test which reproduces the segmentation fault. Can you take a look: https://github.com/xerial/sqlite-jdbc/pull/685

**Comment by pyckle** [comment] 2021-11-08 08:17
@ranjitkollu1 - sqlite_close_v2 will not fix this issue because it's not an issue with the database closing. It's an issue of a prepared statement being finalized while it's in use. There are flows in prepared statements that are not synchronized with the close() flow.

**Closed** 2022-07-29 03:54 UTC
Labels: bug

**Comment by gotson** [comment] 2022-08-01 06:25
This is available in the latest snapshot, please give it a try.
