### ISSUE TITLE
Since the version 3.32.3.3 there is a error like "No suitable driver found for jdbc:sqlite:sample.db"

### ISSUE THREAD

**Issue by wlfcolin** [xerial/sqlite-jdbc#597] opened 2021-04-19 06:40 UTC
@xerial Since the version 3.32.3.3 there is a error like "No suitable driver found for jdbc:sqlite:sample.db", it can't solve by using maven-shade-plugin like this：
```
<transformer implementation="org.apache.maven.plugins.shade.resource.AppendingTransformer">
	<resource>META-INF/services/java.sql.Driver</resource>
</transformer> 
```
However, the version 3.32.3.2 and earlier can work very well.

**Comment by Hilal-Anwar** [comment] 2021-04-19 20:25
You are right a  similar thing happened with me. I was trying to use version 3.34.0.
After trying for hours I gave up and downloaded the jar file https://repo1.maven.org/maven2/org/xerial/sqlite-jdbc/3.34.0/sqlite-jdbc-3.34.0.jar.
Which is a non maven solution.

**Comment by Hilal-Anwar** [comment] 2021-04-20 05:29
Ok , you told that it is working with v3.32.3.2 and lower but i tried with v3.32.3.2 and v3.32.3.1 but didn't worked.
I also tried it with gradle but  it is  working fine with it.

My pom.xml file .I am using java 16.

<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <groupId>org.example</groupId>
    <artifactId>SqliteProject</artifactId>
    <version>1.0-SNAPSHOT</version>

    <properties>
        <maven.compiler.source>16</maven.compiler.source>
        <maven.compiler.target>16</maven.compiler.target>
    </properties>
    <dependencies>
        <dependency>
            <groupId>org.xerial</groupId>
            <artifactId>sqlite-jdbc</artifactId>
            <version>3.32.3.1</version>
            <scope>provided</scope>
        </dependency>

    </dependencies>
    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-shade-plugin</artifactId>
                <version>3.2.4</version>
                <executions>
                    <execution>
                        <goals>
                            <goal>shade</goal>
                        </goals>
                        <configuration>
                            <transformers>
                                <transformer implementation="org.apache.maven.plugins.shade.resource.AppendingTransformer">
                                    <resource>META-INF/spring.handlers</resource>
                                </transformer>
                                <transformer implementation="org.apache.maven.plugins.shade.resource.AppendingTransformer">
                                    <resource>META-INF/spring.schemas</resource>
                                </transformer>
                                <transformer implementation="org.apache.maven.plugins.shade.resource.AppendingTransformer">
                                    <resource>META-INF/services/java.sql.Driver</resource>
                                </transformer>
                            </transformers>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>
</project>


Can you please show how did it worked in your case with v3.32.3.2.

**Comment by wlfcolin** [comment] 2021-04-20 09:05
> Ok , you told that it is working with v3.32.3.2 and lower but i tried with v3.32.3.2 and v3.32.3.1 but didn't worked.
> I also tried it with gradle but it is working fine with it.
> 
> My pom.xml file .I am using java 16.
> 
> 
> 4.0.0
> org.example
> SqliteProject
> 1.0-SNAPSHOT
> 
> ```
> <properties>
>     <maven.compiler.source>16</maven.compiler.source>
>     <maven.compiler.target>16</maven.compiler.target>
> </properties>
> <dependencies>
>     <dependency>
>         <groupId>org.xerial</groupId>
>         <artifactId>sqlite-jdbc</artifactId>
>         <version>3.32.3.1</version>
>         <scope>provided</scope>
>     </dependency>
> 
> </dependencies>
> <build>
>     <plugins>
>         <plugin>
>             <groupId>org.apache.maven.plugins</groupId>
>             <artifactId>maven-shade-plugin</artifactId>
>             <version>3.2.4</version>
>             <executions>
>                 <execution>
>                     <goals>
>                         <goal>shade</goal>
>                     </goals>
>                     <configuration>
>                         <transformers>
>                             <transformer implementation="org.apache.maven.plugins.shade.resource.AppendingTransformer">
>                                 <resource>META-INF/spring.handlers</resource>
>                             </transformer>
>                             <transformer implementation="org.apache.maven.plugins.shade.resource.AppendingTransformer">
>                                 <resource>META-INF/spring.schemas</resource>
>                             </transformer>
>                             <transformer implementation="org.apache.maven.plugins.shade.resource.AppendingTransformer">
>                                 <resource>META-INF/services/java.sql.Driver</resource>
>                             </transformer>
>                         </transformers>
>                     </configuration>
>                 </execution>
>             </executions>
>         </plugin>
>     </plugins>
> </build>
> ```
> 
> Can you please show how did it worked in your case with v3.32.3.2.



this is my pom.xml file with jdk1.7 worked very well
```
<properties>
    <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    <project.reporting.outputEncoding>UTF-8</project.reporting.outputEncoding>
    <maven.compiler.target>1.7</maven.compiler.target>
    <maven.compiler.source>1.7</maven.compiler.source>
  </properties>

  <dependencies>
    <dependency>
      <groupId>org.xerial</groupId>
      <artifactId>sqlite-jdbc</artifactId>
      <version>3.32.3.2</version>
    </dependency>

    <dependency>
      <groupId>junit</groupId>
      <artifactId>junit</artifactId>
      <scope>test</scope>
    </dependency>

  </dependencies>

  <build>
    <plugins>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-shade-plugin</artifactId>
        <version>3.2.4</version>
        <executions>
          <execution>
            <phase>package</phase>
            <goals>
              <goal>shade</goal>
            </goals>
            <configuration>
              <transformers>
                <transformer implementation="org.apache.maven.plugins.shade.resource.AppendingTransformer">
                  <resource>META-INF/services/java.sql.Driver</resource>
                </transformer>
              </transformers>
            </configuration>
          </execution>
        </executions>
      </plugin>
    </plugins>
  </build>
```

**Comment by ddrm86** [comment] 2021-11-22 12:09
Same thing. Except earlier versions do not work for me, and the shade plugin did not work either. Manually downloading the jar and adding it to the classpath is the only thing that worked for me. I am on Windows 10.

**Comment by gotson** [comment] 2022-07-27 12:29
Is this still an issue?

**Comment by nickw1** [comment] 2022-08-10 11:11
Happens for me. On a maven build only. Tried with both 3.32.3.2 and 3.39.2.0, and with and without the shade transformer.

Linux x64 environment, Java 11 (openjdk).

Works ok using simple compilation and run (no maven).

**Comment by gotson** [comment] 2022-08-10 11:56
I still don't quite understand what the problem is to be honest. Is that related to the use of the sample ?

I think a minimum reproducible example would help in understanding what the problem is.

**Comment by nickw1** [comment] 2022-08-10 14:17
OK will create a repo containing the failing project. Yes, I am just testing the sample.
Update: If I use Gradle instead of Maven, it works.

**Comment by nickw1** [comment] 2022-08-10 14:33
OK repo here:

https://github.com/nickw1/sqlite-jdbc-xerial-failing

It's possible my `pom.xml` may contain errors. It was auto-created by Netbeans and modified to link in `sqlite-jdbc` and add the Shade transformation. Many apologies if so!

I do note the file `META-INF/services/java.sql.Driver` is not present on my system, should it be?

**Comment by gotson** [comment] 2022-08-10 15:14
> OK repo here:
> 
> https://github.com/nickw1/sqlite-jdbc-xerial-failing
> 
> It's possible my `pom.xml` may contain errors. It was auto-created by Netbeans and modified to link in `sqlite-jdbc` and add the Shade transformation. Many apologies if so!
> 
> I do note the file `META-INF/services/java.sql.Driver` is not present on my system, should it be?

Thanks. I am by no mean a Maven expert, quite the contrary to be honest.

By removing the `<scope>provided</scope>` it works.

**Comment by gotson** [comment] 2022-08-10 15:35
More findings:
- the Maven Exec plugin doesn't include `provided` deps by default. Remove the `provided` and it works. Else [add](https://stackoverflow.com/a/16042080/2041863) `-Dexec.classpathScope="compile"` on the command line.
- the Maven Exec plugin doesn't use the Jar from my understanding, so the Shade plugin doesn't have any effect when using `mvn exec:java`.
- the Shade plugin doesn't include a `provided` dependency by default. If you want to share the dep, remove the `provided`

**Comment by nickw1** [comment] 2022-08-10 15:50
@gotson many thanks!

**Comment by gotson** [comment] 2022-08-11 01:33
I think the documentation [here](https://github.com/xerial/sqlite-jdbc#hint-for-maven-shade-plugin) is incorrect, it should omit the provided scoped.

I couldn't track any changes that would explain this behaviour introduced in 3.32.3.3.

**Comment by gotson** [comment] 2022-08-13 12:44
I have updated the README and removed `<scope>provided</scope>` from the Maven Shade hint. I'll close this ticket, please comment if there is still an issue.

**Closed by gotson** 2022-08-13 12:44 UTC
Labels: troubleshooting
