### ISSUE TITLE
Incorrect update count after deleting many rows from a table (starting from driver v3.36.0)

### ISSUE THREAD

**Issue by kornilova203** [xerial/sqlite-jdbc#720] opened 2022-02-18 15:46 UTC
How to reproduce:
```java
connection.createStatement().execute("drop table if exists test");
connection.createStatement().execute("create table test (id int not null)");
for (int i = 0; i < 500; i++) {
    connection.createStatement().execute("insert into test values(" + i + ")");
}
System.out.println(connection.createStatement().executeUpdate("delete from test"));
```
Expected output: `500`
Actual output: `501`

Works fine in v3.35.0.1
Incorrect behaviour introduced in v3.36.0

With small number of rows <500 outputs correct value.
If you increase number of rows e.g. 5000 then delta between expected and actual will increase. New driver will output 5010 instead of 5000

**Comment by gotson** [comment] 2022-07-29 06:10
Did you perform some investigation to understand what was happening?

**Comment by kornilova203** [comment] 2022-07-29 09:44
@gotson, no I haven't

**Comment by gotson** [comment] 2022-08-01 03:58
I [added a test](https://github.com/xerial/sqlite-jdbc/commit/708baca10ea291f014b94e9d0c5ecab891296e27#diff-5e5648b3077994096848f2b67a9841022369ac1033826eda2aa1a053cabc51b4) and it [passes in CI](https://github.com/gotson/sqlite-jdbc/actions/runs/2772054679) on all environments, I cannot reproduce your issue.

**Comment by kornilova203** [comment] 2022-08-02 11:57
I confirm that the issue no longer present in 3.39.2-SNAPSHOT (but present in current release 3.36.0.3)
@gotson, do you know when new version will be uploaded to maven central?

**Comment by gotson** [comment] 2022-08-03 01:54
> I confirm that the issue no longer present in 3.39.2-SNAPSHOT (but present in current release 3.36.0.3)

Good catch, indeed i can reproduce with that test on `3.36.0.3`.



> do you know when new version will be uploaded to maven central?

Hopefully this week. I am working on automating the release process.

**Comment by gotson** [comment] 2022-08-04 10:30
@kornilova203 `3.39.2.0` has been released, i will close this.

**Closed by gotson** 2022-08-04 10:30 UTC
Labels: bug
