### ISSUE TITLE
Query is 7 times slower since 3.23.1

### ISSUE THREAD

**Issue by romainguefveneu** [xerial/sqlite-jdbc#516] opened 2020-07-15 06:47 UTC
Hi,
I have a query that is executed in 5s with sqlite-jdbc <= 3.21.0.1 and 35s with sqlite-jdbc >=3.23.1 : 
```
SELECT
    schedulesLinks.tripId,
    schedulesLinks.directionId,
    schedules.stopId,
    schedules.minutes
FROM
    schedulesLinks
    LEFT JOIN schedules ON schedules.tripId = schedulesLinks.tripId
WHERE
    schedules.stopId = 3293
    AND schedulesLinks.directionId = 26
ORDER BY minutes
```

Here is a test project:
[sqlite-jdbc-benchmark.zip](https://github.com/xerial/sqlite-jdbc/files/4923356/sqlite-jdbc-benchmark.zip)

In `build.gradle` you can switch between the "fast version" (`3.21.0.1`) and slow version (`3.32.3`), and then run `SqliteTests`.

Any idea what's going on?

**Comment by xerial** [comment] 2020-07-15 07:27
There are many changes since 3.21.0.1. I guess MMAP option change might have such a huge impact on the query performance: https://github.com/xerial/sqlite-jdbc/pull/328 

Let me revert this and try creating a new version.

**Comment by xerial** [comment] 2020-07-15 07:45
Just shipped 3.32.3.1 without MMAP option. If the performance is still the same level, we should do bisect analysis to see when this performance degradation was introduced.

**Comment by romainguefveneu** [comment] 2020-07-15 11:48
Thanks you for this build but it's still slow.
After some tests, it appears that commit `a76a2a8bddc348a51645be329d419cf6a982f5f1` is the one that introduced the issue.
I reverted the `libsqlitejdbc` lib and my query is fast again.

**Comment by xerial** [comment] 2020-07-15 17:02
It would be great if you can test the same query using sqlite3 command line tools. It seems sqlite 3.23.1 added left-join optimizations https://www.sqlite.org/draft/releaselog/3_23_1.html which might have caused the performance regression.

**Comment by romainguefveneu** [comment] 2020-07-15 17:22
I can't find old binaries for macOS x64, if you have some links i'll be happy to test.

**Comment by xerial** [comment] 2020-07-16 02:47
Using the latest binary is ok to isolate the issue: For example, https://www.sqlite.org/2020/sqlite-tools-osx-x86-3320300.zip

**Comment by xerial** [comment] 2020-07-16 02:59
I tested your query using sqlite 3.24.0 on Mac OS X and it was not slow.

**Comment by xerial** [comment] 2020-07-16 03:20
I also tried simply upgrading only sqlite version based on snappy-java 3.21.0.1 to 3.32.3, and found the performance was still slow. So the java side change is unrelated.

**Comment by xerial** [comment] 2020-07-16 04:33
ok. The conclusion is that this is a performance regression since SQLite 3.23.0 - (I checked 3.22.0, and it was fast enough)

We should consult SQLite maintainers about this change:
https://www.sqlite.org/draft/releaselog/3_23_0.html

There might be a way to disable this optimization by tweaking your left join queries.

**Comment by romainguefveneu** [comment] 2020-07-17 06:26
After digging deeper, it turns out it's the table scan that is slower in 3.23.1, (`SELECT * FROM schedules WHERE schedules.stopId = 3293` is slow). I don't use an index to save 10 Mo and it was fast enough before.

Thank you for your help, I'll try to find a solution on the SQLite forum.

**Comment by xerial** [comment] 2020-07-17 17:18
Thanks! Although the problem is still valid, there is nothing sqlite-jdbc can do for the original SQLite's performance regression. Let me close this ticket.

**Closed by xerial** 2020-07-17 17:18 UTC
